import { CONFIGURE_HOME_NOTIFICATION_ACTIONS_SCRIPT } from "./actions.mjs";
import { CONFIGURE_HOME_NOTIFICATION_LOAD_LIFECYCLE_SCRIPT } from "./load-lifecycle.mjs";
import { CONFIGURE_HOME_NOTIFICATION_PROJECTION_SCRIPT } from "./projection.mjs";

export const CONFIGURE_HOME_RUNTIME_SCRIPT_FRAGMENTS = Object.freeze({
  notificationProjection: CONFIGURE_HOME_NOTIFICATION_PROJECTION_SCRIPT,
  notificationLoadLifecycle: CONFIGURE_HOME_NOTIFICATION_LOAD_LIFECYCLE_SCRIPT,
  notificationActions: CONFIGURE_HOME_NOTIFICATION_ACTIONS_SCRIPT,
});
