import { CALENDAR_PROJECTS_PAGE_SHELL_REFS_SCRIPT } from "./refs.mjs";
import { CALENDAR_PROJECTS_PAGE_SHELL_TEXTAREA_REFS_SCRIPT } from "./textarea-refs.mjs";
import { CALENDAR_PROJECTS_PAGE_SHELL_LOAD_REFS_SCRIPT } from "./load-refs.mjs";
import { CALENDAR_PROJECTS_PAGE_SHELL_COLLECTION_STATE_SCRIPT } from "./collection-state.mjs";
import { CALENDAR_PROJECTS_PAGE_SHELL_EDITOR_STATE_SCRIPT } from "./editor-state.mjs";
import { CALENDAR_PROJECTS_PAGE_SHELL_DERIVED_STATE_SCRIPT } from "./derived-state.mjs";
import { CALENDAR_PROJECTS_PAGE_SHELL_TOP_NAVIGATION_SCRIPT } from "./top-navigation.mjs";

export const CALENDAR_PROJECTS_PAGE_SHELL_FRAGMENTS = Object.freeze({
  refs: CALENDAR_PROJECTS_PAGE_SHELL_REFS_SCRIPT,
  textareaRefs: CALENDAR_PROJECTS_PAGE_SHELL_TEXTAREA_REFS_SCRIPT,
  loadRefs: CALENDAR_PROJECTS_PAGE_SHELL_LOAD_REFS_SCRIPT,
  collectionState: CALENDAR_PROJECTS_PAGE_SHELL_COLLECTION_STATE_SCRIPT,
  editorState: CALENDAR_PROJECTS_PAGE_SHELL_EDITOR_STATE_SCRIPT,
  derivedState: CALENDAR_PROJECTS_PAGE_SHELL_DERIVED_STATE_SCRIPT,
  topNavigation: CALENDAR_PROJECTS_PAGE_SHELL_TOP_NAVIGATION_SCRIPT,
});
