export {
  PlatformResourceActionMenuItem,
  type PlatformResourceActionMenuItemProps,
  type PlatformResourceActionShortcut,
  type PlatformResourceActionShortcutAction,
  type PlatformResourceActionShortcutActions,
  PlatformResourceActionsDivider,
  type PlatformResourceActionsDividerProps,
  PlatformResourceActionsInformation,
  type PlatformResourceActionsInformationProps,
  PlatformResourceActionsMenu,
  type PlatformResourceActionsMenuProps,
  PlatformResourceActionsMetadata,
  type PlatformResourceActionsMetadataItem,
  type PlatformResourceActionsMetadataProps,
  PlatformResourceCopyMenuItem,
  type PlatformResourceCopyMenuItemProps,
  PlatformResourceHeaderActions,
  type PlatformResourceHeaderActionsProps,
  PlatformResourceShareMenuItem,
  type PlatformResourceShareMenuItemProps,
  PlatformResourceVersionHistoryMenuItem,
  type PlatformResourceVersionHistoryMenuItemProps,
  PlatformResourceVersionLabel,
  type PlatformResourceVersionLabelProps,
} from "./platform-resource-header-actions.js";
