import { CONFIGURE_HOME_CONSTANTS_SCRIPT } from "./constants.mjs";
import { CONFIGURE_HOME_NOTIFICATION_RECORDS_SCRIPT } from "./records.mjs";
import { CONFIGURE_HOME_NOTIFICATION_STORAGE_SCRIPT } from "./storage.mjs";

export const CONFIGURE_HOME_DOMAIN_SCRIPT_FRAGMENTS = Object.freeze({
  constants: CONFIGURE_HOME_CONSTANTS_SCRIPT,
  storage: CONFIGURE_HOME_NOTIFICATION_STORAGE_SCRIPT,
  records: CONFIGURE_HOME_NOTIFICATION_RECORDS_SCRIPT,
});
