import { PLATFORM_NAVIGATION_GUARD_MODAL_SCRIPT } from "./components/index.mjs";
import {
  PLATFORM_NAVIGATION_GUARD_LIFECYCLE_SCRIPT,
  PLATFORM_NAVIGATION_GUARD_NAVIGATION_SCRIPT,
  PLATFORM_NAVIGATION_GUARD_REFS_SCRIPT,
  PLATFORM_NAVIGATION_GUARD_STATE_SCRIPT,
} from "./shell/index.mjs";

export const PLATFORM_NAVIGATION_GUARD_APP_SCRIPT_FRAGMENTS = Object.freeze({
  state: PLATFORM_NAVIGATION_GUARD_STATE_SCRIPT,
  refs: PLATFORM_NAVIGATION_GUARD_REFS_SCRIPT,
  navigation: PLATFORM_NAVIGATION_GUARD_NAVIGATION_SCRIPT,
  lifecycle: PLATFORM_NAVIGATION_GUARD_LIFECYCLE_SCRIPT,
  modal: PLATFORM_NAVIGATION_GUARD_MODAL_SCRIPT,
});

export {
  PLATFORM_NAVIGATION_GUARD_LIFECYCLE_SCRIPT,
  PLATFORM_NAVIGATION_GUARD_MODAL_SCRIPT,
  PLATFORM_NAVIGATION_GUARD_NAVIGATION_SCRIPT,
  PLATFORM_NAVIGATION_GUARD_REFS_SCRIPT,
  PLATFORM_NAVIGATION_GUARD_STATE_SCRIPT,
};
