import { GUARDRAILS_APP_HISTORY_CAPTURE_SCRIPT } from "./history-capture.mjs";
import { GUARDRAILS_APP_HISTORY_RESTORE_SCRIPT } from "./history-restore.mjs";
import { GUARDRAILS_APP_NAVIGATION_SCRIPT } from "./navigation.mjs";
import {
  GUARDRAILS_APP_RUNTIME_SCRIPT,
  GUARDRAILS_APP_RUNTIME_SCRIPT_AFTER_FINE_TUNING,
  GUARDRAILS_APP_RUNTIME_SCRIPT_BEFORE_EVALUATIONS,
  GUARDRAILS_APP_RUNTIME_SCRIPT_BEFORE_FINE_TUNING,
  GUARDRAILS_APP_RUNTIME_SCRIPT_BETWEEN_EVALUATIONS_AND_FINE_TUNING,
} from "./runtime/index.mjs";
import { GUARDRAILS_APP_SIDEBAR_ENTRY_SCRIPT } from "./sidebar-entry.mjs";
import { GUARDRAILS_APP_STATE_SCRIPT } from "./state/index.mjs";
import { GUARDRAILS_APP_TOP_NAVIGATION_SCRIPT } from "./top-navigation.mjs";

export {
  GUARDRAILS_APP_RUNTIME_SCRIPT,
  GUARDRAILS_APP_RUNTIME_SCRIPT_AFTER_FINE_TUNING,
  GUARDRAILS_APP_RUNTIME_SCRIPT_BEFORE_EVALUATIONS,
  GUARDRAILS_APP_RUNTIME_SCRIPT_BEFORE_FINE_TUNING,
  GUARDRAILS_APP_RUNTIME_SCRIPT_BETWEEN_EVALUATIONS_AND_FINE_TUNING,
  GUARDRAILS_APP_RUNTIME_SCRIPT_FRAGMENTS,
} from "./runtime/index.mjs";
export {
  GUARDRAILS_APP_STATE_SCRIPT,
  GUARDRAILS_APP_STATE_SCRIPT_FRAGMENTS,
} from "./state/index.mjs";

/** Guardrails-owned fragments mounted inside the shared platform shell. */
export const GUARDRAILS_APP_SCRIPT_FRAGMENTS = Object.freeze({
  state: GUARDRAILS_APP_STATE_SCRIPT,
  runtime: GUARDRAILS_APP_RUNTIME_SCRIPT,
  runtimeBeforeEvaluations: GUARDRAILS_APP_RUNTIME_SCRIPT_BEFORE_EVALUATIONS,
  runtimeBeforeFineTuning: GUARDRAILS_APP_RUNTIME_SCRIPT_BEFORE_FINE_TUNING,
  runtimeBetweenEvaluationsAndFineTuning: GUARDRAILS_APP_RUNTIME_SCRIPT_BETWEEN_EVALUATIONS_AND_FINE_TUNING,
  runtimeAfterFineTuning: GUARDRAILS_APP_RUNTIME_SCRIPT_AFTER_FINE_TUNING,
  navigation: GUARDRAILS_APP_NAVIGATION_SCRIPT,
  historyCapture: GUARDRAILS_APP_HISTORY_CAPTURE_SCRIPT,
  historyRestore: GUARDRAILS_APP_HISTORY_RESTORE_SCRIPT,
  topNavigation: GUARDRAILS_APP_TOP_NAVIGATION_SCRIPT,
  sidebarEntry: GUARDRAILS_APP_SIDEBAR_ENTRY_SCRIPT,
});
