export {
  INFERENCE_APP_SCRIPT_FRAGMENTS,
  INFERENCE_DOMAIN_SCRIPT_FRAGMENTS,
  INFERENCE_PAGE_CASE_SCRIPT,
  INFERENCE_PAGE_CSS,
  INFERENCE_PAGE_SCRIPT_FRAGMENTS,
  INFERENCE_STYLE_FRAGMENTS,
} from "./client/index.mjs";
export { createInferenceService } from "./server/index.mjs";
