import { GUARDRAILS_AGENT_SELECTION_SCRIPT } from "./selection.mjs";
import { GUARDRAILS_AGENT_ADAPTATIONS_SCRIPT } from "./adaptations.mjs";
import { GUARDRAILS_AGENT_BUNDLE_SCRIPT } from "./bundle.mjs";

export const GUARDRAILS_AGENT_DOMAIN_SCRIPT_FRAGMENTS = Object.freeze({
  selection: GUARDRAILS_AGENT_SELECTION_SCRIPT,
  adaptations: GUARDRAILS_AGENT_ADAPTATIONS_SCRIPT,
  bundle: GUARDRAILS_AGENT_BUNDLE_SCRIPT,
});

export const GUARDRAILS_AGENT_DOMAIN_SCRIPT = [
  GUARDRAILS_AGENT_SELECTION_SCRIPT,
  GUARDRAILS_AGENT_ADAPTATIONS_SCRIPT,
  GUARDRAILS_AGENT_BUNDLE_SCRIPT,
].join("");
