import {
  FINE_TUNING_PAGE_EVALUATIONS_SCRIPT,
  FINE_TUNING_PAGE_FOUNDATION_SCRIPT,
  FINE_TUNING_PAGE_JOBS_SCRIPT,
} from "./domain/index.mjs";
import {
  FINE_TUNING_PAGE_CONTROLLER_ACTIONS_SCRIPT,
  FINE_TUNING_PAGE_CONTROLLER_CREATE_MODAL_SCRIPT,
  FINE_TUNING_PAGE_CONTROLLER_DETAIL_SCRIPT,
  FINE_TUNING_PAGE_CONTROLLER_EDITOR_SCRIPT,
  FINE_TUNING_PAGE_CONTROLLER_OVERVIEW_SCRIPT,
  FINE_TUNING_PAGE_CONTROLLER_SETUP_SCRIPT,
  FINE_TUNING_PAGE_CONTROLLER_VERIFICATION_SCRIPT,
  FINE_TUNING_PAGE_CONTROLLER_VIEW_SCRIPT,
} from "./controller/index.mjs";
import { FINE_TUNING_PAGE_ENTRY_SCRIPT } from "./entry.mjs";

export { PLAYGROUND_FINE_TUNING_CSS } from "../styles/page.mjs";

export const FINE_TUNING_PAGE_SCRIPT_FRAGMENTS = Object.freeze({
  foundation: FINE_TUNING_PAGE_FOUNDATION_SCRIPT,
  jobs: FINE_TUNING_PAGE_JOBS_SCRIPT,
  evaluations: FINE_TUNING_PAGE_EVALUATIONS_SCRIPT,
  setup: FINE_TUNING_PAGE_CONTROLLER_SETUP_SCRIPT,
  editor: FINE_TUNING_PAGE_CONTROLLER_EDITOR_SCRIPT,
  verification: FINE_TUNING_PAGE_CONTROLLER_VERIFICATION_SCRIPT,
  actions: FINE_TUNING_PAGE_CONTROLLER_ACTIONS_SCRIPT,
  overview: FINE_TUNING_PAGE_CONTROLLER_OVERVIEW_SCRIPT,
  detail: FINE_TUNING_PAGE_CONTROLLER_DETAIL_SCRIPT,
  createModal: FINE_TUNING_PAGE_CONTROLLER_CREATE_MODAL_SCRIPT,
  view: FINE_TUNING_PAGE_CONTROLLER_VIEW_SCRIPT,
  entry: FINE_TUNING_PAGE_ENTRY_SCRIPT,
});

export const PLAYGROUND_FINE_TUNING_SCRIPT = Object.values(
  FINE_TUNING_PAGE_SCRIPT_FRAGMENTS,
).join("");
