import type {
  PlatformPermissionActionDefinition,
  PlatformPermissionRingDefinition,
} from "./permission-types.js";

export const PLATFORM_PERMISSION_RING_DEFINITIONS: readonly PlatformPermissionRingDefinition[] = [
  {
    id: "ring_1",
    number: 1,
    label: "Ring 1",
    shortLabel: "Local",
    title: "Local workspace",
    description: "Actions that stay inside the selected computer, including local files, shell commands, and local skill runs.",
    defaultAccess: "full_access",
  },
  {
    id: "ring_2",
    number: 2,
    label: "Ring 2",
    shortLabel: "Shared",
    title: "Shared workspace",
    description: "Actions that affect shared Computer Agents resources or send private messages outside the current computer.",
    defaultAccess: "ask_for_permission",
  },
  {
    id: "ring_3",
    number: 3,
    label: "Ring 3",
    shortLabel: "Public",
    title: "Public and irreversible",
    description: "Actions that publish publicly, write to external systems, move money, or expose secrets.",
    defaultAccess: "ask_for_permission",
  },
];

export const PLATFORM_PERMISSION_RING_IDS = PLATFORM_PERMISSION_RING_DEFINITIONS.map((ring) => ring.id);

export const PLATFORM_PERMISSION_ACTION_DEFINITIONS: readonly PlatformPermissionActionDefinition[] = [
  {
    id: "workspace_read",
    ringId: "ring_1",
    label: "Read workspace",
    description: "Read files, directories, logs, and local workspace context.",
  },
  {
    id: "workspace_write",
    ringId: "ring_1",
    label: "Edit workspace",
    description: "Create, update, delete, move, or download files inside the selected computer.",
  },
  {
    id: "local_shell",
    ringId: "ring_1",
    label: "Run local commands",
    description: "Run bash or runtime commands that execute inside the selected computer.",
  },
  {
    id: "local_skill_run",
    ringId: "ring_1",
    label: "Run local skills",
    description: "Use installed skills that operate within the selected computer context.",
  },
  {
    id: "external_read",
    ringId: "ring_2",
    label: "Read external sources",
    description: "Fetch public web pages, package metadata, documentation, or other read-only external context.",
  },
  {
    id: "shared_resource_write",
    ringId: "ring_2",
    label: "Edit shared resources",
    description: "Change shared projects, files, resources, comments, tickets, calendars, or team-visible state.",
  },
  {
    id: "send_email",
    ringId: "ring_2",
    label: "Send private messages",
    description: "Send email, Slack, or other direct messages to known recipients.",
  },
  {
    id: "team_agent_delegation",
    ringId: "ring_2",
    label: "Delegate to agents",
    description: "Create, invoke, or coordinate other agents and team agents.",
  },
  {
    id: "team_workspace_view",
    ringId: "ring_1",
    label: "View team workspace",
    description: "View team members, invitations, shared resources, team activity, and role configuration.",
    subjectTypes: ["team", "team_role"],
  },
  {
    id: "team_member_invite",
    ringId: "ring_2",
    label: "Invite team members",
    description: "Invite humans or agents into the team and assign an initial role.",
    subjectTypes: ["team", "team_role"],
  },
  {
    id: "team_member_remove",
    ringId: "ring_2",
    label: "Remove team members",
    description: "Remove humans or agents from the team membership roster.",
    subjectTypes: ["team", "team_role"],
  },
  {
    id: "team_role_update",
    ringId: "ring_2",
    label: "Change member roles",
    description: "Promote, demote, or otherwise change the role assigned to a team member.",
    subjectTypes: ["team", "team_role"],
  },
  {
    id: "team_shared_resource_manage",
    ringId: "ring_2",
    label: "Manage shared resources",
    description: "Add, remove, or edit projects, computers, agents, templates, and other resources shared with the team.",
    subjectTypes: ["team", "team_role"],
  },
  {
    id: "team_permission_request_review",
    ringId: "ring_2",
    label: "Review permission requests",
    description: "Approve or deny team-scoped permission requests from humans and agents.",
    subjectTypes: ["team", "team_role"],
  },
  {
    id: "team_settings_update",
    ringId: "ring_3",
    label: "Edit team settings",
    description: "Rename the team, change governance settings, delete the team, or alter role permission pages.",
    subjectTypes: ["team", "team_role"],
  },
  {
    id: "organization_workspace_view",
    ringId: "ring_1",
    label: "View organization workspace",
    description: "View organization members, resources, usage, billing, and role configuration.",
    subjectTypes: ["organization_role"],
  },
  {
    id: "organization_member_invite",
    ringId: "ring_2",
    label: "Invite organization members",
    description: "Invite people into the organization and assign an initial role.",
    subjectTypes: ["organization_role"],
  },
  {
    id: "organization_member_remove",
    ringId: "ring_2",
    label: "Remove organization members",
    description: "Remove people from the organization membership roster.",
    subjectTypes: ["organization_role"],
  },
  {
    id: "organization_role_update",
    ringId: "ring_2",
    label: "Change member roles",
    description: "Promote, demote, or otherwise change organization member roles.",
    subjectTypes: ["organization_role"],
  },
  {
    id: "organization_resource_manage",
    ringId: "ring_2",
    label: "Manage organization resources",
    description: "Create, edit, operate, or remove resources owned by the organization.",
    subjectTypes: ["organization_role"],
  },
  {
    id: "organization_billing_manage",
    ringId: "ring_3",
    label: "Manage usage and billing",
    description: "Manage credits, budgets, reservations, usage controls, and billing operations.",
    subjectTypes: ["organization_role"],
  },
  {
    id: "organization_settings_update",
    ringId: "ring_3",
    label: "Edit organization settings",
    description: "Rename the organization and change governance or role-permission settings.",
    subjectTypes: ["organization_role"],
  },
  {
    id: "project_rules_view",
    ringId: "ring_1",
    label: "View project rules",
    description: "Read project rules that guide agents, tickets, and shared execution behavior.",
    subjectTypes: ["project", "project_team_role"],
  },
  {
    id: "project_rules_edit",
    ringId: "ring_2",
    label: "Edit project rules",
    description: "Create, update, or remove project rules used by agents and collaborators.",
    subjectTypes: ["project", "project_team_role"],
  },
  {
    id: "project_access_manage",
    ringId: "ring_3",
    label: "Manage project access",
    description: "Add teams, remove teams, or change project role permission pages.",
    subjectTypes: ["project", "project_team_role"],
  },
  {
    id: "database_schema_read",
    ringId: "ring_1",
    label: "View schema",
    description: "View collections, fields, indexes, and database metadata.",
    subjectTypes: ["database"],
  },
  {
    id: "database_data_read",
    ringId: "ring_1",
    label: "Read data",
    description: "Read documents and values stored in this database.",
    subjectTypes: ["database"],
  },
  {
    id: "database_query",
    ringId: "ring_1",
    label: "Run queries",
    description: "Filter, sort, aggregate, and search database records.",
    subjectTypes: ["database"],
  },
  {
    id: "database_export",
    ringId: "ring_2",
    label: "Export data",
    description: "Download or transmit database records outside the database.",
    subjectTypes: ["database"],
  },
  {
    id: "database_document_create",
    ringId: "ring_2",
    label: "Create documents",
    description: "Add new documents and values to existing collections.",
    subjectTypes: ["database"],
  },
  {
    id: "database_document_update",
    ringId: "ring_2",
    label: "Update documents",
    description: "Change existing documents, fields, and values.",
    subjectTypes: ["database"],
  },
  {
    id: "database_document_delete",
    ringId: "ring_3",
    label: "Delete documents",
    description: "Permanently delete documents or fields from the database.",
    subjectTypes: ["database"],
  },
  {
    id: "database_schema_manage",
    ringId: "ring_3",
    label: "Manage schema",
    description: "Create, rename, or delete collections and change database structure.",
    subjectTypes: ["database"],
  },
  {
    id: "database_access_manage",
    ringId: "ring_3",
    label: "Manage access",
    description: "Share the database and change permissions for teams and collaborators.",
    subjectTypes: ["database"],
  },
  {
    id: "server_source_read",
    ringId: "ring_1",
    label: "View source",
    description: "View source files, configuration, versions, and deployment metadata.",
    subjectTypes: ["server"],
  },
  {
    id: "server_invoke",
    ringId: "ring_1",
    label: "Invoke resource",
    description: "Open a web app or invoke a function through its deployed endpoint.",
    subjectTypes: ["server"],
  },
  {
    id: "server_logs_read",
    ringId: "ring_1",
    label: "View usage and logs",
    description: "View analytics, request logs, runtime output, and deployment history.",
    subjectTypes: ["server"],
  },
  {
    id: "server_source_write",
    ringId: "ring_2",
    label: "Edit source",
    description: "Create, update, rename, or delete source files and configuration.",
    subjectTypes: ["server"],
  },
  {
    id: "server_connection_manage",
    ringId: "ring_2",
    label: "Manage connections",
    description: "Connect or disconnect databases, auth, runtimes, secrets, and payments resources.",
    subjectTypes: ["server"],
  },
  {
    id: "server_deploy",
    ringId: "ring_3",
    label: "Publish deployments",
    description: "Create versions, publish changes, roll back, or change public deployment settings.",
    subjectTypes: ["server"],
  },
  {
    id: "server_access_manage",
    ringId: "ring_3",
    label: "Manage access",
    description: "Share this resource with teams and change their permission policies.",
    subjectTypes: ["server"],
  },
  {
    id: "server_delete",
    ringId: "ring_3",
    label: "Delete resource",
    description: "Permanently delete this function or web app and its managed deployment.",
    subjectTypes: ["server"],
  },
  {
    id: "managed_resource_mutation",
    ringId: "ring_2",
    label: "Change managed resources",
    description: "Create or update Computer Agents databases, functions, web apps, secrets, auth, or other managed resources.",
  },
  {
    id: "public_deploy",
    ringId: "ring_3",
    label: "Publish deployments",
    description: "Deploy or publish public web apps, functions, workflows, or other externally reachable services.",
  },
  {
    id: "github_write",
    ringId: "ring_3",
    label: "Write to GitHub",
    description: "Push commits, create pull requests, merge code, or otherwise write to GitHub repositories.",
  },
  {
    id: "payment_action",
    ringId: "ring_3",
    label: "Move money",
    description: "Create charges, refunds, checkout links, subscriptions, or payment-provider changes.",
  },
  {
    id: "public_message",
    ringId: "ring_3",
    label: "Publish public messages",
    description: "Post to public channels, social accounts, websites, or customer-visible feeds.",
  },
  {
    id: "secret_export",
    ringId: "ring_3",
    label: "Expose secrets",
    description: "Copy, export, transmit, or reveal secrets and credentials outside the secure resource boundary.",
  },
];

export const PLATFORM_PERMISSION_RESOURCE_TYPES = [
  "agents",
  "skills",
  "servers",
  "computers",
  "files",
  "directories",
  "projects",
] as const;

export const PLATFORM_PERMISSION_SUBJECT_TYPES = [
  "agent",
  "project",
  "project_team_role",
  "team",
  "team_role",
  "organization_role",
  "database",
  "server",
  "human_user",
] as const;

export type PlatformPermissionSubjectType = typeof PLATFORM_PERMISSION_SUBJECT_TYPES[number];
