export const IMAGINE_PAGE_CATALOG_SCRIPT = String.raw`          const styleOptions = useMemo(() => [
            { id: "professional", label: "Professional", Icon: Award },
            { id: "editorial", label: "Editorial", Icon: Camera },
            { id: "premium", label: "Premium", Icon: Sparkles },
            { id: "minimal", label: "Minimal", Icon: Minus },
            { id: "cinematic", label: "Cinematic", Icon: Film },
            { id: "studio", label: "Studio", Icon: Crop },
            { id: "lifestyle", label: "Lifestyle", Icon: User },
            { id: "bold", label: "Bold", Icon: Flame },
            { id: "playful", label: "Playful", Icon: Wand2 },
            { id: "technical", label: "Technical", Icon: Code2 },
            { id: "data-driven", label: "Data-driven", Icon: ChartNoAxesColumnIncreasing },
            { id: "product", label: "Product", Icon: Package },
            { id: "social", label: "Social", Icon: MessageCircle },
            { id: "exploratory", label: "Exploratory", Icon: Telescope },
          ], []);
          const aspectRatioOptions = useMemo(() => [
            { value: "", label: "No preference", description: "Let the agent choose the best format" },
            { value: "1:1", label: "1:1", description: "Square composition" },
            { value: "4:5", label: "4:5", description: "Portrait campaign image" },
            { value: "16:9", label: "16:9", description: "Wide landscape image" },
            { value: "9:16", label: "9:16", description: "Vertical story format" },
          ], []);
          const selectedCreateStyleOptions = useMemo(() => {
            const selectedSet = new Set(Array.isArray(templateDraft.defaultStyles) ? templateDraft.defaultStyles : []);
            return styleOptions.filter((option) => selectedSet.has(option.id));
          }, [styleOptions, templateDraft.defaultStyles]);
          const selectedCreateAspectRatioOption = useMemo(() => {
            return aspectRatioOptions.find((option) => option.value === templateDraft.defaultAspectRatio) || aspectRatioOptions[0];
          }, [aspectRatioOptions, templateDraft.defaultAspectRatio]);

          const templates = useMemo(() => [
            {
              id: "product-ads",
              title: "Product ads",
              description: "Launch-ready product scenes, social variants, and campaign visuals.",
              prompt: "Create a premium product ad with a clean studio setup, soft light, and conversion-focused composition.",
              placeholder: "Create a product ad",
              defaultStyles: ["product", "premium", "studio", "professional"],
              Icon: Sparkles,
              imageUrl: "/img/imagine/product-ad.webp",
              tone: "url('/img/imagine/product-ad.webp') center / cover no-repeat",
              aspectRatio: "1086 / 1448",
              size: "large",
            },
            {
              id: "astra-ads",
              title: "AstraFlow ads",
              description: "Sci-fi SaaS launch ads with cinematic product mood and bold conversion copy.",
              prompt: "Create a sci-fi SaaS early-access advertisement with an astronaut product hero, luminous platform blocks, bold launch typography, premium dark-blue lighting, concise offer copy, and a polished conversion-focused call to action.",
              placeholder: "Create an AstraFlow ad",
              defaultStyles: ["product", "premium", "cinematic", "bold"],
              Icon: Sparkles,
              imageUrl: "/img/imagine/astra-ad.webp",
              tone: "url('/img/imagine/astra-ad.webp') center / cover no-repeat",
              aspectRatio: "4 / 5",
              size: "large",
            },
            {
              id: "multi-asset-campaign-set",
              title: "Pitch deck",
              description: "Modern multi-slide pitch decks with sharp narrative, data, and visual hierarchy.",
              prompt: "Create a modern pitch deck that follows the attached slide references: crisp startup narrative, strong page hierarchy, premium black/white/blue visual language, investor-ready copy, and a coherent slide system across every generated asset.",
              placeholder: "Create a pitch deck",
              defaultStyles: ["professional", "minimal", "data-driven", "premium"],
              Icon: LayoutGrid,
              imageUrl: "/img/imagine/pitch-deck/01.webp",
              tone: "url('/img/imagine/pitch-deck/01.webp') center / cover no-repeat",
              aspectRatio: "16 / 9",
              assets: [
                {
                  type: "image",
                  url: "/img/imagine/pitch-deck/01.webp",
                  title: "Problem slide reference",
                  aspectRatio: "16 / 9",
                },
                {
                  type: "image",
                  url: "/img/imagine/pitch-deck/02.webp",
                  title: "Platform overview reference",
                  aspectRatio: "16 / 9",
                },
                {
                  type: "image",
                  url: "/img/imagine/pitch-deck/03.webp",
                  title: "Market validation reference",
                  aspectRatio: "16 / 9",
                },
                {
                  type: "image",
                  url: "/img/imagine/pitch-deck/04.webp",
                  title: "Use case reference",
                  aspectRatio: "16 / 9",
                },
                {
                  type: "image",
                  url: "/img/imagine/pitch-deck/05.webp",
                  title: "Business model reference",
                  aspectRatio: "16 / 9",
                },
              ],
            },
            {
              id: "modern-pitch-deck",
              title: "Modern pitch deck",
              description: "Elegant investor and report slides with editorial type, clean metrics, and operational storytelling.",
              prompt: "Create a modern pitch deck that follows the attached slide references: elegant editorial typography, clean white space, soft green analytical panels, polished metrics, strong platform impact storytelling, and a cohesive report-ready slide system across every generated asset.",
              placeholder: "Create a modern deck",
              defaultStyles: ["professional", "minimal", "data-driven", "premium"],
              Icon: LayoutGrid,
              imageUrl: "/img/imagine/pitch-deck-modern/01.webp",
              tone: "url('/img/imagine/pitch-deck-modern/01.webp') center / cover no-repeat",
              aspectRatio: "16 / 9",
              assets: [
                {
                  type: "image",
                  url: "/img/imagine/pitch-deck-modern/01.webp",
                  title: "Platform impact slide reference",
                  aspectRatio: "16 / 9",
                },
                {
                  type: "image",
                  url: "/img/imagine/pitch-deck-modern/02.webp",
                  title: "Efficiency metrics slide reference",
                  aspectRatio: "16 / 9",
                },
              ],
            },
            {
              id: "classic-pitch-deck",
              title: "Classic pitch deck",
              description: "Clean investor slides with timeless layouts, structured storytelling, and polished presentation hierarchy.",
              prompt: "Create a classic investor pitch deck that follows the attached slide references: clean presentation structure, confident business storytelling, strong section hierarchy, refined typography, crisp visuals, and a cohesive slide system across every generated asset.",
              placeholder: "Create a classic pitch deck",
              defaultStyles: ["professional", "minimal", "data-driven", "premium"],
              Icon: LayoutGrid,
              imageUrl: "/img/imagine/pitch-deck-classic/01.webp",
              tone: "url('/img/imagine/pitch-deck-classic/01.webp') center / cover no-repeat",
              aspectRatio: "16 / 9",
              assets: [
                {
                  type: "image",
                  url: "/img/imagine/pitch-deck-classic/01.webp",
                  title: "Title slide reference",
                  aspectRatio: "16 / 9",
                },
                {
                  type: "image",
                  url: "/img/imagine/pitch-deck-classic/02.webp",
                  title: "Problem and opportunity reference",
                  aspectRatio: "16 / 9",
                },
                {
                  type: "image",
                  url: "/img/imagine/pitch-deck-classic/03.webp",
                  title: "Solution and product reference",
                  aspectRatio: "16 / 9",
                },
                {
                  type: "image",
                  url: "/img/imagine/pitch-deck-classic/04.webp",
                  title: "Business and traction reference",
                  aspectRatio: "16 / 9",
                },
              ],
            },
            {
              id: "luxury-watch-ads",
              title: "Luxury watch ads",
              description: "Premium timepiece visuals with bold type, shine, and dramatic contrast.",
              prompt: "Create a luxury watch advertisement with dramatic lighting, crisp macro detail, bold headline typography, and a premium editorial finish.",
              placeholder: "Create a watch ad",
              defaultStyles: ["product", "premium", "studio", "bold"],
              Icon: Clock,
              imageUrl: "/img/imagine/watch-ad.webp",
              tone: "url('/img/imagine/watch-ad.webp') center / cover no-repeat",
              aspectRatio: "1 / 1",
            },
            {
              id: "video-product-launch",
              title: "Product launch video",
              description: "Short cinematic product videos with motion, pacing, and campaign polish.",
              prompt: "Create a short cinematic product launch video with premium camera movement, crisp lighting, restrained motion graphics, and a clear brand reveal.",
              placeholder: "Create a product launch video",
              defaultStyles: ["product", "premium", "cinematic", "professional"],
              Icon: Film,
              imageUrl: "/img/imagine/product-ad.webp",
              tone: "url('/img/imagine/product-ad.webp') center / cover no-repeat",
              aspectRatio: "16 / 9",
              size: "wide",
              mediaType: "video",
            },
            {
              id: "akita-space-video",
              title: "Akita in space",
              description: "A playful Akita drifting through deep space with cinematic motion.",
              prompt: "Create a playful cinematic video of an Akita floating weightlessly through deep space with gentle camera motion, soft starlight, and a polished sci-fi finish.",
              placeholder: "Create an Akita space video",
              defaultStyles: ["cinematic", "editorial", "premium", "exploratory"],
              Icon: Film,
              videoUrl: "/img/imagine/akita.mp4",
              tone: "linear-gradient(135deg, rgba(5, 9, 20, 0.95), rgba(20, 31, 58, 0.72))",
              aspectRatio: "16 / 9",
              size: "wide",
              mediaType: "video",
            },
            {
              id: "cell-division-video",
              title: "Cell division",
              description: "Close-up microscopic motion for biology, science, and research visuals.",
              prompt: "Create a close-up microscopic video of cell division with organic motion, subtle depth, clean scientific detail, and a polished research-film finish.",
              placeholder: "Create a cell division video",
              defaultStyles: ["cinematic", "technical", "premium", "exploratory"],
              Icon: Film,
              videoUrl: "/img/imagine/cell-division.mp4",
              tone: "linear-gradient(135deg, rgba(5, 12, 10, 0.96), rgba(20, 52, 45, 0.74))",
              aspectRatio: "16 / 9",
              size: "wide",
              mediaType: "video",
            },
            {
              id: "youtube-intro-video",
              title: "YouTube intro",
              description: "Polished creator intros with cinematic pacing, title energy, and channel-ready motion.",
              prompt: "Create a polished YouTube intro video with strong creator branding, cinematic motion, crisp title timing, and a high-retention opening sequence.",
              placeholder: "Create a YouTube intro",
              defaultStyles: ["cinematic", "bold", "premium", "professional"],
              Icon: Film,
              videoUrl: "/img/imagine/youtuber-intro.mp4",
              tone: "linear-gradient(135deg, rgba(6, 8, 18, 0.95), rgba(38, 30, 68, 0.76))",
              aspectRatio: "16 / 9",
              size: "wide",
              mediaType: "video",
            },
            {
              id: "video-cinematic-scene",
              title: "Cinematic scene video",
              description: "Atmospheric short scenes with camera direction and production mood.",
              prompt: "Create a cinematic short video with atmospheric depth, slow camera movement, natural motion, and a premium filmic finish.",
              placeholder: "Create a cinematic scene",
              defaultStyles: ["cinematic", "editorial", "premium", "exploratory"],
              Icon: Film,
              imageUrl: "/img/imagine/lions.webp",
              tone: "url('/img/imagine/lions.webp') center / cover no-repeat",
              aspectRatio: "16 / 9",
              size: "wide",
              mediaType: "video",
            },
            {
              id: "fragrance-ads",
              title: "Fragrance ads",
              description: "Moody perfume visuals with glass detail, texture, and cinematic light.",
              prompt: "Create a moody luxury fragrance advertisement with a glass perfume bottle, tactile environmental texture, cinematic reflections, and refined brand typography.",
              placeholder: "Create a fragrance ad",
              defaultStyles: ["product", "premium", "cinematic", "editorial"],
              Icon: Sparkles,
              imageUrl: "/img/imagine/flacon-ad.webp",
              tone: "url('/img/imagine/flacon-ad.webp') center / cover no-repeat",
              aspectRatio: "1 / 1",
            },
            {
              id: "coffee-ads",
              title: "Coffee ads",
              description: "Warm lifestyle campaigns for coffee launches, blends, and rituals.",
              prompt: "Create a warm premium coffee advertisement with multiple product bags, lifestyle styling, sunlit texture, polished brand typography, and a clear campaign message.",
              placeholder: "Create a coffee ad",
              defaultStyles: ["product", "lifestyle", "premium", "editorial"],
              Icon: ReceiptText,
              imageUrl: "/img/imagine/coffee-ad.webp",
              tone: "url('/img/imagine/coffee-ad.webp') center / cover no-repeat",
              aspectRatio: "1448 / 1086",
              size: "wide",
            },
            {
              id: "beauty-ads",
              title: "Beauty ads",
              description: "Skincare campaign layouts with social proof, product cards, and glow.",
              prompt: "Create a premium beauty advertisement for a skincare brand with an elegant product hero, social-commerce proof, refined editorial typography, and a polished conversion-focused layout.",
              placeholder: "Create a beauty ad",
              defaultStyles: ["product", "premium", "lifestyle", "editorial"],
              Icon: Sparkles,
              imageUrl: "/img/imagine/beauty-ad.webp",
              tone: "url('/img/imagine/beauty-ad.webp') center / cover no-repeat",
              aspectRatio: "1 / 1",
            },
            {
              id: "metal-typography-ads",
              title: "Metal typography ads",
              description: "Premium poster ads with reflective type, product drama, and bold brand presence.",
              prompt: "Create a premium typography-led campaign ad with metallic dimensional lettering, dramatic studio lighting, refined product placement, and a polished high-end brand finish.",
              placeholder: "Create a metal text ad",
              defaultStyles: ["product", "premium", "bold", "studio"],
              Icon: Paintbrush,
              imageUrl: "/img/imagine/metal-text-ad.webp",
              tone: "url('/img/imagine/metal-text-ad.webp') center / cover no-repeat",
              aspectRatio: "1122 / 1402",
              size: "large",
            },
            {
              id: "text-led-ads",
              title: "Text-led ads",
              description: "Clean campaign posters where the message, layout, and product work together.",
              prompt: "Create a clean text-led advertising poster with confident headline typography, elegant product composition, restrained color, and a premium campaign layout.",
              placeholder: "Create a text-led ad",
              defaultStyles: ["product", "minimal", "premium", "professional"],
              Icon: ReceiptText,
              imageUrl: "/img/imagine/text-ad.webp",
              tone: "url('/img/imagine/text-ad.webp') center / cover no-repeat",
              aspectRatio: "1122 / 1402",
              size: "large",
            },
            {
              id: "payment-ads",
              title: "Payment ads",
              description: "Fintech campaign posters for payment products, wallets, and trust.",
              prompt: "Create a premium fintech payment advertisement with a confident customer hero, secure payment messaging, deep blue brand palette, polished iconography, and a clear trust-focused call to action.",
              placeholder: "Create a payment ad",
              defaultStyles: ["product", "professional", "premium", "minimal"],
              Icon: DollarSign,
              imageUrl: "/img/imagine/payment-ad.webp",
              tone: "url('/img/imagine/payment-ad.webp') center / cover no-repeat",
              aspectRatio: "1122 / 1402",
              size: "large",
            },
            {
              id: "logo-branding",
              title: "Logo branding",
              description: "Brand identity visuals with logo marks, mood, and launch polish.",
              prompt: "Create a premium logo branding visual with a distinctive abstract mark, cinematic brand mood, refined typography, and a polished identity presentation for a modern product launch.",
              placeholder: "Create brand visuals",
              defaultStyles: ["premium", "minimal", "cinematic", "professional"],
              Icon: Paintbrush,
              imageUrl: "/img/imagine/logo-branding.webp",
              tone: "url('/img/imagine/logo-branding.webp') center / cover no-repeat",
              aspectRatio: "1 / 1",
            },
            {
              id: "furniture-campaigns",
              title: "Furniture campaigns",
              description: "Interior launch visuals for collections, rooms, and home brands.",
              prompt: "Create a refined furniture campaign poster with a styled interior scene, soft natural light, architectural framing, elegant typography, and premium home brand direction.",
              placeholder: "Create a furniture campaign",
              defaultStyles: ["lifestyle", "premium", "editorial", "product"],
              Icon: Package,
              imageUrl: "/img/imagine/furniture.webp",
              tone: "url('/img/imagine/furniture.webp') center / cover no-repeat",
              aspectRatio: "941 / 1672",
              size: "large",
            },
            {
              id: "sneaker-campaigns",
              title: "Sneaker campaigns",
              description: "Athletic footwear ads with motion, grit, and bold campaign type.",
              prompt: "Create a premium sneaker campaign advertisement with an athletic hero subject, dramatic outdoor lighting, bold oversized typography, performance-focused copy, and polished sportswear brand direction.",
              placeholder: "Create a sneaker campaign",
              defaultStyles: ["product", "bold", "cinematic", "professional"],
              Icon: Flame,
              imageUrl: "/img/imagine/sneakers.webp",
              tone: "url('/img/imagine/sneakers.webp') center / cover no-repeat",
              aspectRatio: "1536 / 1024",
              size: "wide",
            },
            {
              id: "brand-campaigns",
              title: "Brand campaigns",
              description: "Cinematic campaign art directions for bold launches and seasonal moments.",
              prompt: "Design a cinematic brand campaign image with dramatic lighting, clear message, and premium composition.",
              placeholder: "Design a brand campaign",
              defaultStyles: ["professional", "premium", "bold", "editorial"],
              Icon: Paintbrush,
              imageUrl: "/img/imagine/boxer-ad.webp",
              tone: "url('/img/imagine/boxer-ad.webp') center / cover no-repeat",
              aspectRatio: "1672 / 941",
              size: "wide",
            },
            {
              id: "infographics",
              title: "Infographics",
              description: "Clean explainers, diagrams, and visual summaries.",
              prompt: "Create a polished infographic that explains the main idea with clear hierarchy and simple visual metaphors.",
              placeholder: "Make an infographic",
              defaultStyles: ["data-driven", "minimal", "technical", "professional"],
              Icon: LayoutGrid,
              imageUrl: "/img/imagine/raptor.webp",
              tone: "url('/img/imagine/raptor.webp') center / cover no-repeat",
              aspectRatio: "900 / 1200",
              size: "large",
            },
            {
              id: "technical-drawings",
              title: "Technical drawings",
              description: "Exploded views, engineering sketches, and precise product diagrams.",
              prompt: "Create a precise technical drawing with an exploded mechanical view, crisp ink detail, clean annotations, and a polished engineering illustration style.",
              placeholder: "Create a technical drawing",
              defaultStyles: ["technical", "minimal", "professional", "data-driven"],
              Icon: Code2,
              imageUrl: "/img/imagine/engine-drawing.webp",
              tone: "url('/img/imagine/engine-drawing.webp') center / cover no-repeat",
              aspectRatio: "1448 / 1086",
              size: "wide",
            },
            {
              id: "app-screens",
              title: "App screens",
              description: "Mockups, dashboard concepts, and product UI visuals.",
              prompt: "Create a high-end SaaS dashboard concept with dense but readable product UI and realistic data.",
              placeholder: "Mock up an app screen",
              defaultStyles: ["technical", "product", "minimal", "professional"],
              Icon: Monitor,
              imageUrl: "/img/imagine/app-screen.webp",
              tone: "url('/img/imagine/app-screen.webp') center / cover no-repeat",
              aspectRatio: "941 / 1672",
              size: "large",
            },
            {
              id: "editorial",
              title: "Editorial images",
              description: "Magazine-style visuals with artful composition and premium texture.",
              prompt: "Create an editorial hero image with artful composition, cinematic lighting, and premium visual texture.",
              placeholder: "Create an editorial image",
              defaultStyles: ["editorial", "cinematic", "premium"],
              Icon: Camera,
              imageUrl: "/img/imagine/panther.webp",
              tone: "url('/img/imagine/panther.webp') center / cover no-repeat",
              aspectRatio: "1038 / 1515",
              size: "large",
            },
            {
              id: "social-posts",
              title: "Social posts",
              description: "Vertical posts, carousel-ready creative, and high-impact feed visuals.",
              prompt: "Create a social media campaign visual with bold typography, strong hierarchy, and a premium feed-ready composition.",
              placeholder: "Create a social post",
              defaultStyles: ["social", "bold", "playful"],
              Icon: ImageIcon,
              imageUrl: "/img/imagine/social-post.webp",
              tone: "url('/img/imagine/social-post.webp') center / cover no-repeat",
              aspectRatio: "1024 / 1536",
              size: "large",
            },
            {
              id: "restaurant-ads",
              title: "Restaurant ads",
              description: "Menu launches, food posters, and local campaign visuals.",
              prompt: "Create a premium restaurant ad for a seasonal dish with appetizing food photography, elegant typography, a price badge, and a clear call to action.",
              placeholder: "Create a restaurant ad",
              defaultStyles: ["food", "premium", "editorial", "professional"],
              Icon: ReceiptText,
              imageUrl: "/img/imagine/salad-ad.webp",
              tone: "url('/img/imagine/salad-ad.webp') center / cover no-repeat",
              aspectRatio: "1 / 1",
            },
            {
              id: "comparison-ads",
              title: "Comparison ads",
              description: "Before-and-after creative that makes product value obvious.",
              prompt: "Create a polished before-and-after comparison ad with two clear panels, concise benefit copy, expressive illustration, and premium product branding.",
              placeholder: "Create a comparison ad",
              defaultStyles: ["campaign", "minimal", "bold", "professional"],
              Icon: Split,
              imageUrl: "/img/imagine/comparison-ad.webp",
              tone: "url('/img/imagine/comparison-ad.webp') center / cover no-repeat",
              aspectRatio: "1 / 1",
            },
            {
              id: "data-visuals",
              title: "Data visuals",
              description: "Charts, report covers, and visualized insights.",
              prompt: "Create a sophisticated data visualization artwork for a business report, with charts integrated naturally.",
              placeholder: "Visualize this data",
              defaultStyles: ["data-driven", "professional", "minimal"],
              Icon: ChartNoAxesColumnIncreasing,
              imageUrl: "/img/imagine/data-vis.webp",
              tone: "url('/img/imagine/data-vis.webp') center / cover no-repeat",
              aspectRatio: "1672 / 941",
              size: "wide",
            },
            {
              id: "fashion-campaigns",
              title: "Fashion campaigns",
              description: "Editorial looks, lookbook visuals, and polished campaign assets.",
              prompt: "Create a high-end fashion campaign image with editorial styling, premium lighting, and a strong brand-forward composition.",
              placeholder: "Create a fashion campaign",
              defaultStyles: ["editorial", "premium", "studio", "professional"],
              Icon: Wand2,
              imageUrl: "/img/imagine/fashion.webp",
              tone: "url('/img/imagine/fashion.webp') center / cover no-repeat",
              aspectRatio: "900 / 1200",
              size: "large",
            },
            {
              id: "portrait-studio",
              title: "Portrait studio",
              description: "Refined profile portraits, creator images, and personal-brand visuals.",
              prompt: "Create a refined studio portrait with natural expression, premium lighting, and a clean personal-brand composition.",
              placeholder: "Create a portrait",
              defaultStyles: ["portrait", "studio", "professional", "premium"],
              Icon: Camera,
              imageUrl: "/img/imagine/woman-portrait.webp",
              tone: "url('/img/imagine/woman-portrait.webp') center / cover no-repeat",
              aspectRatio: "1024 / 1536",
              size: "large",
            },
            {
              id: "animated-characters",
              title: "Animated characters",
              description: "Playful character art for stories, campaigns, and product mascots.",
              prompt: "Create a charming animated character image with expressive personality, rich color, and clean storybook composition.",
              placeholder: "Create a character",
              defaultStyles: ["playful", "illustrated", "bold"],
              Icon: Sparkles,
              imageUrl: "/img/imagine/animated-dog.webp",
              tone: "url('/img/imagine/animated-dog.webp') center / cover no-repeat",
              aspectRatio: "1086 / 1448",
              size: "large",
            },
            {
              id: "cinematic-wildlife",
              title: "Cinematic wildlife",
              description: "Dramatic animals, nature stories, and atmospheric campaign visuals.",
              prompt: "Create a cinematic wildlife image with dramatic lighting, atmospheric depth, and premium editorial composition.",
              placeholder: "Create a wildlife scene",
              defaultStyles: ["cinematic", "editorial", "bold"],
              Icon: Telescope,
              imageUrl: "/img/imagine/lions.webp",
              tone: "url('/img/imagine/lions.webp') center / cover no-repeat",
              aspectRatio: "1448 / 1086",
              size: "wide",
            },
            {
              id: "concept-art",
              title: "Concept art",
              description: "Worldbuilding, environments, and visual exploration.",
              prompt: "Create concept art for a futuristic workspace with cinematic depth and production-ready detail.",
              placeholder: "Create concept art",
              defaultStyles: ["exploratory", "cinematic", "bold"],
              Icon: Telescope,
              imageUrl: "/img/imagine/wolf.webp",
              tone: "url('/img/imagine/wolf.webp') center / cover no-repeat",
              aspectRatio: "1672 / 941",
              size: "wide",
            },
          ], []);

`;
