import { IMAGINE_PAGE_FOUNDATION_SCRIPT } from "./foundation.mjs";
import { IMAGINE_PAGE_TEMPLATE_MEDIA_SCRIPT } from "./template-media.mjs";
import { IMAGINE_PAGE_CONTROLLER_SCRIPT } from "./controller.mjs";
import { IMAGINE_PAGE_CATALOG_SCRIPT } from "./catalog.mjs";
import { IMAGINE_PAGE_TEMPLATE_COLLECTION_SCRIPT } from "./template-collection.mjs";
import { IMAGINE_PAGE_TEMPLATE_EDITOR_SCRIPT } from "./template-editor.mjs";
import { IMAGINE_PAGE_COMPOSER_SCRIPT } from "./composer.mjs";
import { IMAGINE_PAGE_GENERATION_SCRIPT } from "./generation.mjs";
import { IMAGINE_PAGE_VIEW_SCRIPT } from "./view.mjs";

export const IMAGINE_PAGE_SCRIPT_FRAGMENTS = Object.freeze({
  foundation: IMAGINE_PAGE_FOUNDATION_SCRIPT,
  templateMedia: IMAGINE_PAGE_TEMPLATE_MEDIA_SCRIPT,
  controller: IMAGINE_PAGE_CONTROLLER_SCRIPT,
  catalog: IMAGINE_PAGE_CATALOG_SCRIPT,
  templateCollection: IMAGINE_PAGE_TEMPLATE_COLLECTION_SCRIPT,
  templateEditor: IMAGINE_PAGE_TEMPLATE_EDITOR_SCRIPT,
  composer: IMAGINE_PAGE_COMPOSER_SCRIPT,
  generation: IMAGINE_PAGE_GENERATION_SCRIPT,
  view: IMAGINE_PAGE_VIEW_SCRIPT,
});

export const IMAGINE_PAGE_SCRIPT = [
  IMAGINE_PAGE_FOUNDATION_SCRIPT,
  IMAGINE_PAGE_TEMPLATE_MEDIA_SCRIPT,
  IMAGINE_PAGE_CONTROLLER_SCRIPT,
  IMAGINE_PAGE_CATALOG_SCRIPT,
  IMAGINE_PAGE_TEMPLATE_COLLECTION_SCRIPT,
  IMAGINE_PAGE_TEMPLATE_EDITOR_SCRIPT,
  IMAGINE_PAGE_COMPOSER_SCRIPT,
  IMAGINE_PAGE_GENERATION_SCRIPT,
  IMAGINE_PAGE_VIEW_SCRIPT,
].join("");
