import { METRONOME_PAGE_CONTROLLER_SCRIPT } from "./controller.mjs";
import { METRONOME_PAGE_EDITOR_SCRIPT } from "./editor.mjs";
import { METRONOME_PAGE_INSPECTOR_SCRIPT } from "./inspector.mjs";
import { METRONOME_PAGE_MODALS_SCRIPT } from "./modals.mjs";
import { METRONOME_PAGE_OVERVIEW_SCRIPT } from "./overview.mjs";
import { METRONOME_PAGE_SHELL_SCRIPT } from "./shell.mjs";

export const METRONOME_PAGE_RUNTIME_SCRIPT = [
  METRONOME_PAGE_SHELL_SCRIPT,
  METRONOME_PAGE_CONTROLLER_SCRIPT,
  METRONOME_PAGE_OVERVIEW_SCRIPT,
  METRONOME_PAGE_INSPECTOR_SCRIPT,
  METRONOME_PAGE_EDITOR_SCRIPT,
  METRONOME_PAGE_MODALS_SCRIPT,
].join("\n");
