import { GUARDRAILS_AGENT_PAGE_MODEL_SCRIPT } from "./model.mjs";
import { GUARDRAILS_AGENT_PAGE_ACTIONS_SCRIPT } from "./actions.mjs";
import { GUARDRAILS_AGENT_PAGE_VIEW_SCRIPT } from "./view.mjs";

export const GUARDRAILS_AGENT_PAGE_SCRIPT_FRAGMENTS = Object.freeze({
  model: GUARDRAILS_AGENT_PAGE_MODEL_SCRIPT,
  actions: GUARDRAILS_AGENT_PAGE_ACTIONS_SCRIPT,
  view: GUARDRAILS_AGENT_PAGE_VIEW_SCRIPT,
});

export const GUARDRAILS_AGENT_PAGE_SCRIPT = [
  GUARDRAILS_AGENT_PAGE_MODEL_SCRIPT,
  GUARDRAILS_AGENT_PAGE_ACTIONS_SCRIPT,
  GUARDRAILS_AGENT_PAGE_VIEW_SCRIPT,
].join("");
