import { GUARDRAILS_MODEL_SCRIPT } from "./model.mjs";
import { GUARDRAILS_VERSIONS_SCRIPT } from "./versions.mjs";
import { GUARDRAILS_DIFF_SCRIPT } from "./diff.mjs";
import { GUARDRAILS_PERSISTENCE_SCRIPT } from "./persistence.mjs";

export const GUARDRAILS_DOMAIN_RUNTIME_SCRIPT_FRAGMENTS = Object.freeze({
  model: GUARDRAILS_MODEL_SCRIPT,
  versions: GUARDRAILS_VERSIONS_SCRIPT,
  diff: GUARDRAILS_DIFF_SCRIPT,
  persistence: GUARDRAILS_PERSISTENCE_SCRIPT,
});

export const GUARDRAILS_DOMAIN_RUNTIME_SCRIPT = [
  GUARDRAILS_MODEL_SCRIPT,
  GUARDRAILS_VERSIONS_SCRIPT,
  GUARDRAILS_DIFF_SCRIPT,
  GUARDRAILS_PERSISTENCE_SCRIPT,
].join("");
