import { RESOURCE_CREATION_HOST_SCRIPT } from "./components/index.mjs";
import {
  RESOURCE_CREATION_ACTIONS_SCRIPT,
  RESOURCE_CREATION_STATE_SCRIPT,
} from "./shell/index.mjs";

export const RESOURCE_CREATION_APP_SCRIPT_FRAGMENTS = Object.freeze({
  state: RESOURCE_CREATION_STATE_SCRIPT,
  actions: RESOURCE_CREATION_ACTIONS_SCRIPT,
  host: RESOURCE_CREATION_HOST_SCRIPT,
});

export {
  RESOURCE_CREATION_ACTIONS_SCRIPT,
  RESOURCE_CREATION_HOST_SCRIPT,
  RESOURCE_CREATION_STATE_SCRIPT,
};
