import {
  EVALUATIONS_PAGE_EXECUTION_SCRIPT,
  EVALUATIONS_PAGE_FORMATTING_SCRIPT,
  EVALUATIONS_PAGE_FOUNDATION_SCRIPT,
  EVALUATIONS_PAGE_PERSISTENCE_SCRIPT,
  EVALUATIONS_PAGE_RECORDS_SCRIPT,
  EVALUATIONS_PAGE_RESOURCES_SCRIPT,
  EVALUATIONS_PAGE_RUNS_SCRIPT,
  EVALUATIONS_PAGE_SOURCE_THREADS_SCRIPT,
  EVALUATIONS_PAGE_VERSIONS_SCRIPT,
} from "./domain/index.mjs";
import {
  EVALUATIONS_PAGE_CONTROLLER_ACCESS_SCRIPT,
  EVALUATIONS_PAGE_CONTROLLER_ACTIONS_SCRIPT,
  EVALUATIONS_PAGE_CONTROLLER_CASE_DETAIL_SCRIPT,
  EVALUATIONS_PAGE_CONTROLLER_CHARTS_SCRIPT,
  EVALUATIONS_PAGE_CONTROLLER_DIALOGS_SCRIPT,
  EVALUATIONS_PAGE_CONTROLLER_EDITORS_SCRIPT,
  EVALUATIONS_PAGE_CONTROLLER_SETUP_SCRIPT,
  EVALUATIONS_PAGE_CONTROLLER_TABLES_SCRIPT,
  EVALUATIONS_PAGE_CONTROLLER_THREAD_CASES_SCRIPT,
  EVALUATIONS_PAGE_CONTROLLER_VERSION_DIALOGS_SCRIPT,
  EVALUATIONS_PAGE_CONTROLLER_VERSIONS_SCRIPT,
  EVALUATIONS_PAGE_CONTROLLER_VIEWS_SCRIPT,
} from "./controller/index.mjs";

export const EVALUATIONS_PAGE_SCRIPT_FRAGMENTS = Object.freeze({
  foundation: EVALUATIONS_PAGE_FOUNDATION_SCRIPT,
  versions: EVALUATIONS_PAGE_VERSIONS_SCRIPT,
  persistence: EVALUATIONS_PAGE_PERSISTENCE_SCRIPT,
  runs: EVALUATIONS_PAGE_RUNS_SCRIPT,
  resources: EVALUATIONS_PAGE_RESOURCES_SCRIPT,
  records: EVALUATIONS_PAGE_RECORDS_SCRIPT,
  sourceThreads: EVALUATIONS_PAGE_SOURCE_THREADS_SCRIPT,
  execution: EVALUATIONS_PAGE_EXECUTION_SCRIPT,
  formatting: EVALUATIONS_PAGE_FORMATTING_SCRIPT,
  setup: EVALUATIONS_PAGE_CONTROLLER_SETUP_SCRIPT,
  versionActions: EVALUATIONS_PAGE_CONTROLLER_VERSIONS_SCRIPT,
  editors: EVALUATIONS_PAGE_CONTROLLER_EDITORS_SCRIPT,
  actions: EVALUATIONS_PAGE_CONTROLLER_ACTIONS_SCRIPT,
  access: EVALUATIONS_PAGE_CONTROLLER_ACCESS_SCRIPT,
  threadCases: EVALUATIONS_PAGE_CONTROLLER_THREAD_CASES_SCRIPT,
  charts: EVALUATIONS_PAGE_CONTROLLER_CHARTS_SCRIPT,
  tables: EVALUATIONS_PAGE_CONTROLLER_TABLES_SCRIPT,
  caseDetail: EVALUATIONS_PAGE_CONTROLLER_CASE_DETAIL_SCRIPT,
  views: EVALUATIONS_PAGE_CONTROLLER_VIEWS_SCRIPT,
  versionDialogs: EVALUATIONS_PAGE_CONTROLLER_VERSION_DIALOGS_SCRIPT,
  dialogs: EVALUATIONS_PAGE_CONTROLLER_DIALOGS_SCRIPT,
});

export const PLAYGROUND_EVALUATIONS_SCRIPT = Object.values(
  EVALUATIONS_PAGE_SCRIPT_FRAGMENTS,
).join("");
