import { IMAGINE_TEMPLATE_PAGE_FOUNDATION_SCRIPT } from "./foundation.mjs";
import { IMAGINE_TEMPLATE_PAGE_CONTROLLER_SCRIPT } from "./controller.mjs";
import { IMAGINE_TEMPLATE_PAGE_CONTEXT_SCRIPT } from "./context.mjs";
import { IMAGINE_TEMPLATE_PAGE_GENERATION_SCRIPT } from "./generation.mjs";
import { IMAGINE_TEMPLATE_PAGE_ACTIONS_SCRIPT } from "./actions.mjs";
import { IMAGINE_TEMPLATE_PAGE_SETTINGS_SCRIPT } from "./settings.mjs";
import { IMAGINE_TEMPLATE_PAGE_SHARING_SCRIPT } from "./sharing.mjs";
import { IMAGINE_TEMPLATE_PAGE_VIEW_SCRIPT } from "./view.mjs";

export const IMAGINE_TEMPLATE_PAGE_SCRIPT_FRAGMENTS = Object.freeze({
  foundation: IMAGINE_TEMPLATE_PAGE_FOUNDATION_SCRIPT,
  controller: IMAGINE_TEMPLATE_PAGE_CONTROLLER_SCRIPT,
  context: IMAGINE_TEMPLATE_PAGE_CONTEXT_SCRIPT,
  generation: IMAGINE_TEMPLATE_PAGE_GENERATION_SCRIPT,
  actions: IMAGINE_TEMPLATE_PAGE_ACTIONS_SCRIPT,
  settings: IMAGINE_TEMPLATE_PAGE_SETTINGS_SCRIPT,
  sharing: IMAGINE_TEMPLATE_PAGE_SHARING_SCRIPT,
  view: IMAGINE_TEMPLATE_PAGE_VIEW_SCRIPT,
});

export const IMAGINE_TEMPLATE_PAGE_SCRIPT = [
  IMAGINE_TEMPLATE_PAGE_FOUNDATION_SCRIPT,
  IMAGINE_TEMPLATE_PAGE_CONTROLLER_SCRIPT,
  IMAGINE_TEMPLATE_PAGE_CONTEXT_SCRIPT,
  IMAGINE_TEMPLATE_PAGE_GENERATION_SCRIPT,
  IMAGINE_TEMPLATE_PAGE_ACTIONS_SCRIPT,
  IMAGINE_TEMPLATE_PAGE_SETTINGS_SCRIPT,
  IMAGINE_TEMPLATE_PAGE_SHARING_SCRIPT,
  IMAGINE_TEMPLATE_PAGE_VIEW_SCRIPT,
].join("");
