import { METRONOME_CANVAS_RUNTIME_SCRIPT } from "./canvas-components.mjs";
import { METRONOME_EXECUTION_RUNTIME_SCRIPT } from "./execution-and-code.mjs";
import { METRONOME_TEMPLATES_RUNTIME_SCRIPT } from "./templates-and-graph.mjs";
import { METRONOME_TRIGGERS_RUNTIME_SCRIPT } from "./triggers-and-contracts.mjs";
import { METRONOME_WORKFLOW_DOMAIN_RUNTIME_SCRIPT } from "./workflow-domain.mjs";

export const METRONOME_DOMAIN_RUNTIME_SCRIPT = [
  METRONOME_TRIGGERS_RUNTIME_SCRIPT,
  METRONOME_TEMPLATES_RUNTIME_SCRIPT,
  METRONOME_WORKFLOW_DOMAIN_RUNTIME_SCRIPT,
  METRONOME_EXECUTION_RUNTIME_SCRIPT,
  METRONOME_CANVAS_RUNTIME_SCRIPT,
].join("\n");
