import { GUARDRAILS_PAGE_CONTROLLER_SCRIPT } from "./controller.mjs";
import { GUARDRAILS_PAGE_VERSION_ACTIONS_SCRIPT } from "./version-actions.mjs";
import { GUARDRAILS_PAGE_VERSION_VIEWS_SCRIPT } from "./version-views.mjs";
import { GUARDRAILS_PAGE_EDITOR_SCRIPT } from "./editor.mjs";
import { GUARDRAILS_PAGE_TABLE_SCRIPT } from "./table.mjs";
import { GUARDRAILS_PAGE_VIEW_SCRIPT } from "./view.mjs";

export const GUARDRAILS_PAGE_RUNTIME_SCRIPT_FRAGMENTS = Object.freeze({
  controller: GUARDRAILS_PAGE_CONTROLLER_SCRIPT,
  versionActions: GUARDRAILS_PAGE_VERSION_ACTIONS_SCRIPT,
  versionViews: GUARDRAILS_PAGE_VERSION_VIEWS_SCRIPT,
  editor: GUARDRAILS_PAGE_EDITOR_SCRIPT,
  table: GUARDRAILS_PAGE_TABLE_SCRIPT,
  view: GUARDRAILS_PAGE_VIEW_SCRIPT,
});

export const GUARDRAILS_PAGE_RUNTIME_SCRIPT = [
  GUARDRAILS_PAGE_CONTROLLER_SCRIPT,
  GUARDRAILS_PAGE_VERSION_ACTIONS_SCRIPT,
  GUARDRAILS_PAGE_VERSION_VIEWS_SCRIPT,
  GUARDRAILS_PAGE_EDITOR_SCRIPT,
  GUARDRAILS_PAGE_TABLE_SCRIPT,
  GUARDRAILS_PAGE_VIEW_SCRIPT,
].join("");
