import { ONBOARDING_HOST_SCRIPT } from "./host.mjs";
import { ONBOARDING_LIFECYCLE_SCRIPT } from "./lifecycle.mjs";
import { ONBOARDING_NAVIGATION_SCRIPT } from "./navigation.mjs";
import { ONBOARDING_RUNTIME_SCRIPT } from "./runtime.mjs";
import { ONBOARDING_STATE_SCRIPT } from "./state.mjs";

export const ONBOARDING_SHELL_SCRIPT_FRAGMENTS = Object.freeze({
  state: ONBOARDING_STATE_SCRIPT,
  navigation: ONBOARDING_NAVIGATION_SCRIPT,
  lifecycle: ONBOARDING_LIFECYCLE_SCRIPT,
  runtime: ONBOARDING_RUNTIME_SCRIPT,
  host: ONBOARDING_HOST_SCRIPT,
});

export {
  ONBOARDING_HOST_SCRIPT,
  ONBOARDING_LIFECYCLE_SCRIPT,
  ONBOARDING_NAVIGATION_SCRIPT,
  ONBOARDING_RUNTIME_SCRIPT,
  ONBOARDING_STATE_SCRIPT,
};

