import { IMAGINE_TEMPLATE_CONFIGURATION_CSS } from "./configuration.mjs";
import { IMAGINE_TEMPLATE_LEGACY_PREVIEW_CSS } from "./legacy-preview.mjs";
import { IMAGINE_TEMPLATE_DETAIL_SURFACE_CSS } from "./detail-surface.mjs";
import { IMAGINE_TEMPLATE_COMPOSER_SETTINGS_CSS } from "./composer-settings.mjs";

export const IMAGINE_TEMPLATE_PAGE_CSS_FRAGMENTS = Object.freeze({
  configuration: IMAGINE_TEMPLATE_CONFIGURATION_CSS,
  legacyPreview: IMAGINE_TEMPLATE_LEGACY_PREVIEW_CSS,
  detailSurface: IMAGINE_TEMPLATE_DETAIL_SURFACE_CSS,
  composerSettings: IMAGINE_TEMPLATE_COMPOSER_SETTINGS_CSS,
});

export const IMAGINE_TEMPLATE_PAGE_CSS = [
  IMAGINE_TEMPLATE_CONFIGURATION_CSS,
  IMAGINE_TEMPLATE_LEGACY_PREVIEW_CSS,
  IMAGINE_TEMPLATE_DETAIL_SURFACE_CSS,
  IMAGINE_TEMPLATE_COMPOSER_SETTINGS_CSS,
].join("");
