import { CALENDAR_PROJECTS_PAGE_ATTACHMENT_REMOVAL_SCRIPT } from "./attachment-removal.mjs";
import { CALENDAR_PROJECTS_PAGE_SCHEDULE_DIALOG_VIEW_SCRIPT } from "./schedule-dialog-view.mjs";

export const CALENDAR_PROJECTS_PAGE_CONNECTOR_FRAGMENTS = Object.freeze({
  attachmentRemoval: CALENDAR_PROJECTS_PAGE_ATTACHMENT_REMOVAL_SCRIPT,
  scheduleDialogView: CALENDAR_PROJECTS_PAGE_SCHEDULE_DIALOG_VIEW_SCRIPT,
});
