export const GUARDRAILS_APP_VALUES_SCRIPT = `        const [guardrailSets, setGuardrailSets] = useState([]);
        const [selectedGuardrailSetId, setSelectedGuardrailSetId] = useState("");
        const [guardrailsBackendSyncState, setGuardrailsBackendSyncState] = useState({ status: "idle", error: "" });
        const [guardrailsPageMode, setGuardrailsPageMode] = useState("overview");
        const [guardrailsToolbarPopover, setGuardrailsToolbarPopover] = useState("");
        const [guardrailSetActionMenuId, setGuardrailSetActionMenuId] = useState("");
        const [guardrailDetailActionsMenuOpen, setGuardrailDetailActionsMenuOpen] = useState(false);
        const [guardrailPublishMenuOpen, setGuardrailPublishMenuOpen] = useState(false);
        const [guardrailVersionsHeaderMenuOpen, setGuardrailVersionsHeaderMenuOpen] = useState(false);
        const [guardrailVersionsSidebarOpen, setGuardrailVersionsSidebarOpen] = useState(false);
        const [guardrailVersionState, setGuardrailVersionState] = useState({ status: "idle", message: "", error: "" });
        const [guardrailVersionModal, setGuardrailVersionModal] = useState(null);
        const [guardrailVersionModalVisible, setGuardrailVersionModalVisible] = useState(false);
        const [guardrailVersionModalClosing, setGuardrailVersionModalClosing] = useState(false);
        const [guardrailVersionNameDraft, setGuardrailVersionNameDraft] = useState("");
        const [guardrailVersionDescriptionDraft, setGuardrailVersionDescriptionDraft] = useState("");
        const [isGuardrailVersionDescriptionEditing, setIsGuardrailVersionDescriptionEditing] = useState(false);
        const [guardrailVersionChangesState, setGuardrailVersionChangesState] = useState(null);
        const [openGuardrailVersionMenuId, setOpenGuardrailVersionMenuId] = useState("");
        const allGuardrailSets = useMemo(() => getPlaygroundAllGuardrailSets(guardrailSets), [guardrailSets]);
`;
