import { CALENDAR_PROJECTS_PAGE_COMMENTS_SCRIPT } from "./comments.mjs";
import { CALENDAR_PROJECTS_PAGE_SKILLS_SCRIPT } from "./skills.mjs";
import { CALENDAR_PROJECTS_PAGE_SCHEDULE_DIALOG_SCRIPT } from "./schedule-dialog.mjs";
import { CALENDAR_PROJECTS_PAGE_PARENT_PICKER_SCRIPT } from "./parent-picker.mjs";
import { CALENDAR_PROJECTS_PAGE_TASK_TYPE_SCRIPT } from "./task-type.mjs";
import { CALENDAR_PROJECTS_PAGE_PARENT_SELECTION_SCRIPT } from "./parent-selection.mjs";
import { CALENDAR_PROJECTS_PAGE_DRAFT_UPDATES_SCRIPT } from "./draft-updates.mjs";
import { CALENDAR_PROJECTS_PAGE_TASK_NAVIGATION_SCRIPT } from "./task-navigation.mjs";

export const CALENDAR_PROJECTS_PAGE_ACTION_FRAGMENTS = Object.freeze({
  comments: CALENDAR_PROJECTS_PAGE_COMMENTS_SCRIPT,
  skills: CALENDAR_PROJECTS_PAGE_SKILLS_SCRIPT,
  scheduleDialog: CALENDAR_PROJECTS_PAGE_SCHEDULE_DIALOG_SCRIPT,
  parentPicker: CALENDAR_PROJECTS_PAGE_PARENT_PICKER_SCRIPT,
  taskType: CALENDAR_PROJECTS_PAGE_TASK_TYPE_SCRIPT,
  parentSelection: CALENDAR_PROJECTS_PAGE_PARENT_SELECTION_SCRIPT,
  draftUpdates: CALENDAR_PROJECTS_PAGE_DRAFT_UPDATES_SCRIPT,
  taskNavigation: CALENDAR_PROJECTS_PAGE_TASK_NAVIGATION_SCRIPT,
});
