export const ORGANIZATIONS_STATE_PRIMARY_SCRIPT = `	        const organizationPageRef = useRef(null);
	        const organizationPageLoadAbortControllerRef = useRef(null);
	        const organizationPageLoadSequenceRef = useRef(0);
	        const [activeOrganizationId, setActiveOrganizationId] = useState(() => readPlaygroundActiveOrganizationId());
	        const activeOrganizationResourceScopeKeyRef = useRef(String(activeOrganizationId || "").trim() || "__personal__");
	        const [organizationPageLoading, setOrganizationPageLoading] = useState(false);
        const [organizationPageError, setOrganizationPageError] = useState("");
        const [organizationPageOrganizations, setOrganizationPageOrganizations] = useState([]);
	        const [organizationPageSelectedOrganizationId, setOrganizationPageSelectedOrganizationId] = useState("");
	        const [organizationPageActiveTab, setOrganizationPageActiveTab] = useState("organization");
	        const [organizationPageBillingSection, setOrganizationPageBillingSection] = useState("costs-plans");
	        const [organizationPagePendingDestination, setOrganizationPagePendingDestination] = useState(null);
	        const [organizationPageSelectedRoleId, setOrganizationPageSelectedRoleId] = useState("member");
	        const [organizationPageRoleMembersPopover, setOrganizationPageRoleMembersPopover] = useState("");
	        const [organizationPermissionChartAnimationKey, setOrganizationPermissionChartAnimationKey] = useState(0);
	        const [organizationPageMembers, setOrganizationPageMembers] = useState([]);
	        const [organizationPageInvitations, setOrganizationPageInvitations] = useState([]);
	        const [organizationPageResources, setOrganizationPageResources] = useState([]);
	        const [organizationResourceSearchQuery, setOrganizationResourceSearchQuery] = useState("");
	        const [organizationResourceFilter, setOrganizationResourceFilter] = useState("all");
	        const [organizationResourceViewMode, setOrganizationResourceViewMode] = useState("list");
	        const [organizationResourceToolbarPopover, setOrganizationResourceToolbarPopover] = useState("");
	        const [organizationResourceSort, setOrganizationResourceSort] = useState("resource");
	        const [organizationResourceSortDirection, setOrganizationResourceSortDirection] = useState("asc");
`;
