export const RESOURCE_TEMPLATE_TYPES = Object.freeze([
  { id: "all", label: "All templates" },
  { id: "metronome", label: "Metronomes" },
  { id: "file", label: "Files" },
  { id: "web_app", label: "Web Apps" },
  { id: "function", label: "Functions" },
  { id: "database", label: "Databases" },
  { id: "imagine", label: "Imagine" },
]);

export const RESOURCE_TEMPLATE_CATALOG = Object.freeze([
  {
    id: "customer-support-email-metronome",
    title: "Customer Support Email Workflow",
    type: "metronome",
    typeLabel: "Metronome",
    projectTypes: ["customer_sales", "business_operations"],
    featured: true,
    summary: "Turn inbound support emails into researched, reviewed replies.",
    description: "An email-triggered workflow that classifies the request, searches project context, drafts an answer, routes uncertain cases through a condition, and sends a reply.",
    capabilities: ["Email trigger", "Knowledge search", "Conditional review", "Reply automation"],
    workflowSteps: [
      "Trigger when a support email arrives.",
      "Classify intent, urgency, account, and product area.",
      "Search project files, knowledge sources, and connected resources.",
      "Draft the response and branch to review when confidence is low.",
      "Send the approved answer back to the customer.",
    ],
    outputs: ["Support reply", "Thread summary", "Task when review is required"],
    setup: ["Connect email", "Attach support knowledge files", "Choose reply agent"],
    difficulty: "Advanced",
    estimatedSetup: "12 min",
  },
  {
    id: "weekly-executive-briefing",
    title: "Weekly Executive Briefing",
    type: "metronome",
    typeLabel: "Metronome",
    projectTypes: ["business_operations", "finance_analysis", "research_knowledge"],
    featured: true,
    summary: "Generate a recurring brief from metrics, files, and recent activity.",
    description: "A scheduled workflow for pulling project activity, current metrics, important files, and external context into one concise operating brief.",
    capabilities: ["Scheduled run", "File reading", "Web search", "Report writing"],
    workflowSteps: ["Collect recent project activity.", "Read KPI files and dashboards.", "Research external changes if needed.", "Write a short executive brief."],
    outputs: ["Weekly brief", "Action items", "Risk summary"],
    setup: ["Set schedule", "Select source folders", "Choose brief recipients"],
    difficulty: "Intermediate",
    estimatedSetup: "8 min",
  },
  {
    id: "campaign-content-calendar",
    title: "Campaign Content Calendar",
    type: "metronome",
    typeLabel: "Metronome",
    projectTypes: ["marketing_campaign"],
    featured: true,
    summary: "Plan, generate, and review content for a campaign launch.",
    description: "A recurring campaign workflow that creates briefs, drafts posts, tracks approvals, and prepares follow-up tasks for performance review.",
    capabilities: ["Campaign planning", "Creative generation", "Approval checks", "Performance follow-up"],
    workflowSteps: ["Read campaign brief.", "Generate weekly content ideas.", "Draft posts and creative prompts.", "Create approval tasks.", "Schedule performance review."],
    outputs: ["Content calendar", "Creative prompts", "Approval tasks"],
    setup: ["Attach campaign brief", "Choose channels", "Define launch date"],
    difficulty: "Intermediate",
    estimatedSetup: "10 min",
  },
  {
    id: "launch-landing-page",
    title: "Launch Landing Page",
    type: "web_app",
    typeLabel: "Web App",
    projectTypes: ["marketing_campaign", "software_development"],
    featured: true,
    summary: "A shippable landing page scaffold for launches and waitlists.",
    description: "A responsive web app template with hero copy, proof points, signup intent, analytics placeholders, and project-aware handoff notes.",
    capabilities: ["Frontend scaffold", "Responsive layout", "Analytics-ready", "Deployable app"],
    workflowSteps: ["Create a web app resource.", "Generate launch copy from the project brief.", "Deploy and connect tracking."],
    outputs: ["Landing page", "Deployable web app", "Launch checklist"],
    setup: ["Add campaign brief", "Choose brand assets", "Connect analytics later"],
    difficulty: "Beginner",
    estimatedSetup: "6 min",
  },
  {
    id: "product-status-dashboard",
    title: "Product Status Dashboard",
    type: "web_app",
    typeLabel: "Web App",
    projectTypes: ["software_development", "business_operations"],
    featured: false,
    summary: "A dashboard for releases, users, resources, and operational health.",
    description: "A web app template that surfaces release progress, active users, incidents, tasks, and resource status for software and operations projects.",
    capabilities: ["Dashboard UI", "Resource health", "Task overview", "Deployment ready"],
    workflowSteps: ["Create dashboard app.", "Connect project resources.", "Display project progress and activity."],
    outputs: ["Status dashboard", "Resource overview", "Deployment task"],
    setup: ["Select project resources", "Choose metrics", "Deploy app"],
    difficulty: "Intermediate",
    estimatedSetup: "9 min",
  },
  {
    id: "webhook-intake-function",
    title: "Webhook Intake Function",
    type: "function",
    typeLabel: "Function",
    projectTypes: ["software_development", "business_operations", "customer_sales"],
    featured: true,
    summary: "Receive webhooks, validate payloads, and create project tasks.",
    description: "A backend function for signed webhook intake, payload normalization, task creation, and audit-friendly response handling.",
    capabilities: ["Webhook validation", "Task creation", "Secrets", "Structured logging"],
    workflowSteps: ["Create function.", "Read shared secret.", "Validate incoming payload.", "Create task or resource event."],
    outputs: ["Function endpoint", "Task creation hook", "Audit event"],
    setup: ["Add signing secret", "Choose target project", "Define payload fields"],
    difficulty: "Intermediate",
    estimatedSetup: "10 min",
  },
  {
    id: "payment-reconciliation-function",
    title: "Payment Reconciliation Function",
    type: "function",
    typeLabel: "Function",
    projectTypes: ["finance_analysis", "business_operations"],
    featured: false,
    summary: "Normalize payment events and reconcile them against project records.",
    description: "A function template that accepts payment provider events, checks existing database records, and creates follow-up tasks for mismatches.",
    capabilities: ["Payment events", "Database lookup", "Mismatch tasks", "Audit trail"],
    workflowSteps: ["Receive provider event.", "Normalize customer and amount.", "Compare database record.", "Create task for mismatch."],
    outputs: ["Reconciliation endpoint", "Mismatch report", "Follow-up task"],
    setup: ["Connect payment provider", "Select database", "Add signing secret"],
    difficulty: "Advanced",
    estimatedSetup: "14 min",
  },
  {
    id: "customer-crm-database",
    title: "Customer CRM Database",
    type: "database",
    typeLabel: "Database",
    projectTypes: ["customer_sales", "business_operations"],
    featured: true,
    summary: "A structured customer, account, and follow-up database.",
    description: "A database template for accounts, contacts, conversations, deals, follow-ups, and support context that agents can reference.",
    capabilities: ["Accounts", "Contacts", "Follow-ups", "Agent-readable records"],
    workflowSteps: ["Create database.", "Add customer schema.", "Connect support or sales workflows."],
    outputs: ["CRM database", "Starter collections", "Follow-up fields"],
    setup: ["Choose project", "Import customers", "Connect email workflow"],
    difficulty: "Beginner",
    estimatedSetup: "7 min",
  },
  {
    id: "investor-metrics-database",
    title: "Investor Metrics Database",
    type: "database",
    typeLabel: "Database",
    projectTypes: ["finance_analysis", "business_operations"],
    featured: false,
    summary: "Track operating metrics, assumptions, and investor updates.",
    description: "A finance-oriented database template for monthly metrics, assumptions, variance notes, and investor-ready summaries.",
    capabilities: ["Metric tracking", "Forecast notes", "Variance analysis", "Reporting"],
    workflowSteps: ["Create metric collections.", "Import spreadsheet data.", "Generate update summaries."],
    outputs: ["Metrics database", "Monthly update fields", "Analysis tasks"],
    setup: ["Upload spreadsheet", "Map metrics", "Choose reporting cadence"],
    difficulty: "Intermediate",
    estimatedSetup: "9 min",
  },
  {
    id: "research-source-library",
    title: "Research Source Library",
    type: "file",
    typeLabel: "Files",
    projectTypes: ["research_knowledge"],
    featured: true,
    summary: "A source library structure for evidence-backed research projects.",
    description: "A file workspace template with folders for source material, notes, reports, citations, and exported deliverables.",
    capabilities: ["Source folders", "Citation manifest", "Report structure", "Evidence hygiene"],
    workflowSteps: ["Create source folders.", "Store primary and secondary sources.", "Generate a citation manifest."],
    outputs: ["Folder structure", "README", "Source manifest"],
    setup: ["Upload source files", "Define research question", "Choose report format"],
    difficulty: "Beginner",
    estimatedSetup: "5 min",
  },
  {
    id: "brand-asset-workspace",
    title: "Brand Asset Workspace",
    type: "file",
    typeLabel: "Files",
    projectTypes: ["marketing_campaign"],
    featured: false,
    summary: "Organize briefs, references, generated assets, and final campaign files.",
    description: "A project file template for campaign briefs, brand references, creative generations, approvals, and final exports.",
    capabilities: ["Creative folders", "Reference assets", "Approval folders", "Final exports"],
    workflowSteps: ["Create campaign folders.", "Attach brand references.", "Route generated assets into review folders."],
    outputs: ["Asset folders", "Creative README", "Export structure"],
    setup: ["Upload brand assets", "Add campaign brief", "Define output channels"],
    difficulty: "Beginner",
    estimatedSetup: "5 min",
  },
  {
    id: "product-hero-media-pack",
    title: "Product Hero Image & Video Pack",
    type: "imagine",
    typeLabel: "Imagine",
    projectTypes: ["marketing_campaign", "software_development"],
    featured: true,
    summary: "Generate hero visuals, ad variants, and short motion assets.",
    description: "An Imagine template pack for producing product hero images, social variations, and optional short video assets from one creative direction.",
    capabilities: ["Image generation", "Video generation", "Multi-asset prompts", "Campaign variants"],
    workflowSteps: ["Choose visual direction.", "Generate hero image set.", "Create video variant when needed.", "Save outputs to project."],
    outputs: ["Hero image", "Ad variants", "Short video option"],
    setup: ["Attach product references", "Choose model defaults", "Define channel sizes"],
    difficulty: "Intermediate",
    estimatedSetup: "8 min",
  },
]);
