export {
  RESOURCE_TEMPLATE_CATALOG,
  RESOURCE_TEMPLATE_CATALOG as MARKETPLACE_TEMPLATE_CATALOG,
  RESOURCE_TEMPLATE_TYPES,
  RESOURCE_TEMPLATE_TYPES as MARKETPLACE_TEMPLATE_TYPES,
} from "./catalog.mjs";
