import { CALENDAR_PROJECTS_PAGE_SAVE_STATE_SCRIPT } from "./save-state.mjs";
import { CALENDAR_PROJECTS_PAGE_ATTACHMENTS_SCRIPT } from "./attachments.mjs";
import { CALENDAR_PROJECTS_PAGE_EDITOR_FORMATTING_SCRIPT } from "./editor-formatting.mjs";
import { CALENDAR_PROJECTS_PAGE_DRAFT_FACTORY_SCRIPT } from "./draft-factory.mjs";
import { CALENDAR_PROJECTS_PAGE_STATUS_SCRIPT } from "./status.mjs";
import { CALENDAR_PROJECTS_PAGE_LOADING_SCRIPT } from "./loading.mjs";
import { CALENDAR_PROJECTS_PAGE_PERSISTENCE_SCRIPT } from "./persistence.mjs";

export const CALENDAR_PROJECTS_PAGE_DATA_FRAGMENTS = Object.freeze({
  saveState: CALENDAR_PROJECTS_PAGE_SAVE_STATE_SCRIPT,
  attachments: CALENDAR_PROJECTS_PAGE_ATTACHMENTS_SCRIPT,
  editorFormatting: CALENDAR_PROJECTS_PAGE_EDITOR_FORMATTING_SCRIPT,
  draftFactory: CALENDAR_PROJECTS_PAGE_DRAFT_FACTORY_SCRIPT,
  status: CALENDAR_PROJECTS_PAGE_STATUS_SCRIPT,
  loading: CALENDAR_PROJECTS_PAGE_LOADING_SCRIPT,
  persistence: CALENDAR_PROJECTS_PAGE_PERSISTENCE_SCRIPT,
});
