import { GUARDRAILS_APP_FORMATTING_SCRIPT } from "./formatting.mjs";
import { GUARDRAILS_APP_ACTIONS_SCRIPT } from "./actions.mjs";
import { GUARDRAILS_APP_BACKEND_SCRIPT } from "./backend.mjs";
import {
  GUARDRAILS_APP_LIFECYCLE_SCRIPT,
  GUARDRAILS_APP_LIFECYCLE_SCRIPT_AFTER_FINE_TUNING,
  GUARDRAILS_APP_LIFECYCLE_SCRIPT_BEFORE_EVALUATIONS,
  GUARDRAILS_APP_LIFECYCLE_SCRIPT_BEFORE_FINE_TUNING,
  GUARDRAILS_APP_LIFECYCLE_SCRIPT_BETWEEN_EVALUATIONS_AND_FINE_TUNING,
} from "./lifecycle.mjs";

export const GUARDRAILS_APP_RUNTIME_SCRIPT_FRAGMENTS = Object.freeze({
  formatting: GUARDRAILS_APP_FORMATTING_SCRIPT,
  actions: GUARDRAILS_APP_ACTIONS_SCRIPT,
  backend: GUARDRAILS_APP_BACKEND_SCRIPT,
  lifecycle: GUARDRAILS_APP_LIFECYCLE_SCRIPT,
  lifecycleBeforeEvaluations: GUARDRAILS_APP_LIFECYCLE_SCRIPT_BEFORE_EVALUATIONS,
  lifecycleBeforeFineTuning: GUARDRAILS_APP_LIFECYCLE_SCRIPT_BEFORE_FINE_TUNING,
  lifecycleBetweenEvaluationsAndFineTuning: GUARDRAILS_APP_LIFECYCLE_SCRIPT_BETWEEN_EVALUATIONS_AND_FINE_TUNING,
  lifecycleAfterFineTuning: GUARDRAILS_APP_LIFECYCLE_SCRIPT_AFTER_FINE_TUNING,
});

export const GUARDRAILS_APP_RUNTIME_SCRIPT_BEFORE_FINE_TUNING = [
  GUARDRAILS_APP_FORMATTING_SCRIPT,
  GUARDRAILS_APP_ACTIONS_SCRIPT,
  GUARDRAILS_APP_BACKEND_SCRIPT,
  GUARDRAILS_APP_LIFECYCLE_SCRIPT_BEFORE_FINE_TUNING,
].join("");

export const GUARDRAILS_APP_RUNTIME_SCRIPT_BEFORE_EVALUATIONS = [
  GUARDRAILS_APP_FORMATTING_SCRIPT,
  GUARDRAILS_APP_ACTIONS_SCRIPT,
  GUARDRAILS_APP_BACKEND_SCRIPT,
  GUARDRAILS_APP_LIFECYCLE_SCRIPT_BEFORE_EVALUATIONS,
].join("");

export const GUARDRAILS_APP_RUNTIME_SCRIPT_BETWEEN_EVALUATIONS_AND_FINE_TUNING =
  GUARDRAILS_APP_LIFECYCLE_SCRIPT_BETWEEN_EVALUATIONS_AND_FINE_TUNING;

export const GUARDRAILS_APP_RUNTIME_SCRIPT_AFTER_FINE_TUNING =
  GUARDRAILS_APP_LIFECYCLE_SCRIPT_AFTER_FINE_TUNING;

export const GUARDRAILS_APP_RUNTIME_SCRIPT = [
  GUARDRAILS_APP_FORMATTING_SCRIPT,
  GUARDRAILS_APP_ACTIONS_SCRIPT,
  GUARDRAILS_APP_BACKEND_SCRIPT,
  GUARDRAILS_APP_LIFECYCLE_SCRIPT,
].join("");
