import { CALENDAR_PROJECTS_PAGE_CALENDAR_VIEW_SCRIPT } from "./calendar.mjs";
import { CALENDAR_PROJECTS_PAGE_UPGRADE_MODAL_SCRIPT } from "./upgrade-modal.mjs";
import { CALENDAR_PROJECTS_PAGE_STANDALONE_WORKSPACE_SCRIPT } from "./standalone-workspace.mjs";

export const CALENDAR_PROJECTS_PAGE_VIEW_FRAGMENTS = Object.freeze({
  calendar: CALENDAR_PROJECTS_PAGE_CALENDAR_VIEW_SCRIPT,
  upgradeModal: CALENDAR_PROJECTS_PAGE_UPGRADE_MODAL_SCRIPT,
  standaloneWorkspace: CALENDAR_PROJECTS_PAGE_STANDALONE_WORKSPACE_SCRIPT,
});
