import {
  FINE_TUNING_CT_PER_DOLLAR,
  clampScore,
  compactFineTuningReferenceMetadata,
  computeTokensToUsd,
  hasPlainObjectContent,
  normalizeResponseArray,
  normalizeString,
  normalizeTokenCount,
  normalizeUsdCost,
  readFirstPlainObject,
  readPlainObject,
  sanitizeReferenceText,
} from "./primitives.mjs";

import {
  getFineTuningBaselineRun,
} from "./evaluations.mjs";

export function buildFineTuningPrompt({ targetAgent, fineTunerAgent, environment, evaluationSets, instructions, verifyAfter, jobId, nextVersionNumber }) {
  const caseCount = evaluationSets.reduce((sum, set) => sum + (Array.isArray(set.dataRows) ? set.dataRows.length : 0), 0);
  const evaluationSummary = evaluationSets.map((set, index) => {
    const latestRun = getFineTuningBaselineRun(set);
    const rows = (Array.isArray(set.dataRows) ? set.dataRows : []).slice(0, 8).map((row, rowIndex) => ({
      index: rowIndex + 1,
      input: String(row?.input || "").slice(0, 1200),
      expectedOutput: String(row?.expectedOutput || row?.expected_output || "").slice(0, 1200),
      evaluationGuidance: String(row?.evaluationGuidance || row?.evaluation_guidance || "").slice(0, 800),
      runCount: Number(row?.runCount || row?.run_count || 1) || 1,
    }));
    return {
      index: index + 1,
      id: set.id,
      name: set.name,
      activeVersionId: set.activeVersionId,
      activeVersionNumber: set.activeVersionNumber,
      latestRun,
      caseCount: Array.isArray(set.dataRows) ? set.dataRows.length : 0,
      sampleCases: rows,
    };
  });
  return [
    "You are running a fine-tuning analysis job for an AI agent platform.",
    "Your job is to create and publish a safer, higher-performing version of the target agent from the selected evaluation evidence.",
    "This is an execution task, not a recommendation task. The user approved this exact publish action by starting the fine-tune job.",
    "Do not ask whether to continue, do not browse unrelated platform state, and do not stop after an analysis plan.",
    "Focus on concrete instruction changes, missing constraints, failure modes, and evaluation-driven improvements.",
    "Immutable target-agent identity: keep the target agent name exactly \"" + (targetAgent.name || "Agent") + "\". Do not rename the agent, change its avatar, owner, model, skills, guardrails, team access, or other configuration. Only improve the instructions.",
    "",
    "Required execution path:",
    "1. Adapt the target agent instructions directly from the evidence below.",
    "2. Write the complete improved target-agent instructions to /tmp/fine-tuned-agent-instructions.md.",
    "3. Run exactly this publish command:",
    "   python3 /workspace/.claude/skills/computer-agents/scripts/computer-agents.py fine-tuning publish-agent-version --target-agent-id " + targetAgent.id + " --instructions-file /tmp/fine-tuned-agent-instructions.md --job-id " + (jobId || "fine_tune_job") + " --label \"Fine-Tuned Version\" --description \"Generated by fine-tuning job " + (jobId || "") + "\"",
    "4. If the command succeeds, return a concise summary of the evidence, the exact instruction changes, and the published version id.",
    "5. If the command fails, return the exact command error. Do not switch to curl or hand-written API calls.",
    "",
    "Do not run agents list, threads list, evaluations list, versions list, or generic API discovery unless the required publish command fails because a required ID is invalid. All required IDs and evaluation evidence are included here.",
    "",
    "Target agent:",
    JSON.stringify({
      id: targetAgent.id,
      name: targetAgent.name,
      immutableName: targetAgent.name,
      model: targetAgent.model,
      description: targetAgent.description,
      instructions: targetAgent.instructions,
      nextVersionNumber,
    }, null, 2),
    "",
    "Fine-tuner agent executing this job:",
    JSON.stringify({
      id: fineTunerAgent.id,
      name: fineTunerAgent.name,
      model: fineTunerAgent.model,
    }, null, 2),
    "",
    "Execution computer:",
    JSON.stringify({ id: environment.id, name: environment.name }, null, 2),
    "",
    "User focus:",
    instructions ? instructions : "No extra focus supplied.",
    "",
    "Evaluation data:",
    JSON.stringify({
      evaluationSetCount: evaluationSets.length,
      caseCount,
      verifyAfter: Boolean(verifyAfter),
      evaluationSets: evaluationSummary,
    }, null, 2),
    "",
    "Return the final fine-tuning summary only after the version creation command has succeeded or failed with a concrete error."
  ].join("\n");
}

export function decodeMaybeEscapedText(value) {
  let text = String(value || "");
  const escapedNewlineCount = (text.match(/\\n/g) || []).length;
  if (escapedNewlineCount >= 2) {
    text = text
      .replace(/\\r\\n/g, "\n")
      .replace(/\\n/g, "\n")
      .replace(/\\t/g, "\t")
      .replace(/\\"/g, "\"");
  }
  return text;
}

export function sanitizeFineTuningAnalysisText(value) {
  let text = decodeMaybeEscapedText(value)
    .replace(/\r\n/g, "\n")
    .replace(/\n{4,}/g, "\n\n\n")
    .trim();
  if (!text) return "";

  const rawPayloadIndex = text.search(/(?:^|\s)(?:data|event):\s*\{/);
  if (rawPayloadIndex > 0) {
    text = text.slice(0, rawPayloadIndex).trim();
  }
  text = text
    .split("\n")
    .filter((line) => {
      const trimmed = line.trim();
      if (!trimmed) return true;
      if (/^(event|id|retry):\s*/i.test(trimmed)) return false;
      if (/^data:\s*(?:\{|\[|\"type\")/i.test(trimmed)) return false;
      if (/^\{\"\s*type\"\s*:/.test(trimmed)) return false;
      if (/^\{\"type\":/.test(trimmed)) return false;
      return true;
    })
    .join("\n")
    .trim();
  return text.length > 2400 ? text.slice(0, 2400).trimEnd() + "\n\n..." : text;
}

export function extractStringFromPayloadValue(value) {
  if (typeof value === "string") return value;
  if (Array.isArray(value)) {
    return value.map(extractStringFromPayloadValue).filter(Boolean).join("");
  }
  if (value && typeof value === "object") {
    return extractTextFromStreamPayload(value);
  }
  return "";
}

export function extractTextFromStreamPayload(payload) {
  if (!payload || typeof payload !== "object" || Array.isArray(payload)) return "";
  const direct = [
    payload.output_text,
    payload.outputText,
    payload.summary,
    payload.text,
    payload.delta,
    payload.content,
    payload.message?.content,
    payload.choices?.[0]?.delta?.content,
    payload.choices?.[0]?.message?.content,
  ].map(extractStringFromPayloadValue).find((value) => String(value || "").trim());
  if (direct) return direct;
  const responseOutputText = extractStringFromPayloadValue(payload.response?.output_text || payload.response?.outputText);
  if (responseOutputText) return responseOutputText;
  const output = payload.response?.output || payload.output || payload.data?.output;
  if (Array.isArray(output)) {
    const value = output.map((item) => {
      if (!item || typeof item !== "object") return "";
      return extractStringFromPayloadValue(item.content || item.text || item.output_text || item.outputText || item);
    }).filter(Boolean).join("");
    if (value) return value;
  }
  if (payload.data && typeof payload.data === "object" && !Array.isArray(payload.data)) {
    return extractTextFromStreamPayload(payload.data);
  }
  return "";
}

export function extractStreamSummary(streamText) {
  const text = String(streamText || "");
  if (!text.trim()) return "";
  const deltaCandidates = [];
  const fullCandidates = [];
  text.split(/\r?\n/).forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed === "[DONE]") return;
    if (/^(event|id|retry):\s*/i.test(trimmed)) return;
    const payload = trimmed.startsWith("data:") ? trimmed.slice(5).trim() : trimmed;
    if (!payload || payload === "[DONE]") return;
    try {
      const parsed = JSON.parse(payload);
      const value = sanitizeFineTuningAnalysisText(extractTextFromStreamPayload(parsed));
      if (!value) return;
      const type = String(parsed.type || parsed.event || "").toLowerCase();
      if (type.includes("completed") || type.includes("message") || parsed.response || parsed.output) {
        fullCandidates.push(value);
      } else {
        deltaCandidates.push(value);
      }
    } catch {
      if (!payload.startsWith("{") && !payload.startsWith("[") && !/^data:/i.test(payload)) {
        deltaCandidates.push(payload);
      }
    }
  });
  const bestFull = fullCandidates
    .sort((left, right) => right.length - left.length)[0];
  const summary = bestFull || deltaCandidates.join("");
  return sanitizeFineTuningAnalysisText(summary || text);
}

export function buildProposedInstructions(agent, evaluationSets, instructions, analysis) {
  const baseInstructions = String(agent.instructions || "").trim() || "You are " + agent.name + ". Complete the user's task carefully and accurately.";
  const focus = normalizeString(instructions);
  const setNames = evaluationSets.map((set) => set.name).filter(Boolean).join(", ");
  const improvementNotes = [
    "",
    "Fine-tuning notes:",
    "- Optimize behavior against: " + (setNames || "the selected evaluation sets") + ".",
    "- Prefer explicit reasoning about expected outputs before finalizing the response.",
    "- When evaluation guidance is present, treat it as a hard scoring rubric.",
    "- Keep answers concise unless the task requires structured detail.",
    focus ? "- User focus: " + focus : "",
    analysis ? "- Analysis summary: " + analysis.replace(/\s+/g, " ").slice(0, 900) : "",
  ].filter(Boolean).join("\n");
  return baseInstructions + "\n" + improvementNotes;
}

export function preserveFineTuningAgentName(agent, snapshot = {}) {
  const source = snapshot && typeof snapshot === "object" && !Array.isArray(snapshot) ? snapshot : {};
  return {
    ...source,
    name: normalizeString(agent?.name || source.name || "Agent") || "Agent",
  };
}

export function buildAgentSnapshot(agent, instructions) {
  return preserveFineTuningAgentName(agent, {
    name: agent.name,
    description: agent.description,
    model: agent.model,
    instructions,
    enabledSkills: Array.isArray(agent.enabledSkills) ? agent.enabledSkills : [],
    guardrails: Array.isArray(agent.guardrails) ? agent.guardrails : Array.isArray(agent.metadata?.guardrails) ? agent.metadata.guardrails : [],
    metadata: {
      ...(agent.metadata || {}),
    },
  });
}

export function buildFineTuningDiffFilesFromSnapshots(beforeSnapshot, afterSnapshot) {
  return [
    {
      id: "instructions",
      filePath: "agent/instructions.md",
      beforeContent: beforeSnapshot.instructions || "",
      afterContent: afterSnapshot.instructions || "",
    },
    {
      id: "configuration",
      filePath: "agent/configuration.json",
      beforeContent: JSON.stringify({
        name: beforeSnapshot.name,
        model: beforeSnapshot.model,
        enabledSkills: beforeSnapshot.enabledSkills,
        guardrails: beforeSnapshot.guardrails,
      }, null, 2) + "\n",
      afterContent: JSON.stringify({
        name: afterSnapshot.name,
        model: afterSnapshot.model,
        enabledSkills: afterSnapshot.enabledSkills,
        guardrails: afterSnapshot.guardrails,
      }, null, 2) + "\n",
    },
  ];
}

export function buildFineTuningDiffFiles(agent, proposedInstructions) {
  return buildFineTuningDiffFilesFromSnapshots(
    buildAgentSnapshot(agent, String(agent.instructions || "")),
    buildAgentSnapshot(agent, proposedInstructions)
  );
}

export function buildEvaluationRunReferences(evaluationSets, verifyAfter, improvementScore) {
  return evaluationSets.map((set, index) => {
    const beforeRun = getFineTuningBaselineRun(set);
    const beforeScore = clampScore(beforeRun?.averageScore || 0);
    return {
      evaluationSetId: set.id,
      evaluationSetName: set.name,
      beforeRunId: beforeRun?.id || "",
      beforeRunLabel: beforeRun?.label || "",
      beforeScore,
      beforeCostUsd: normalizeUsdCost(beforeRun?.costUsd || beforeRun?.cost_usd) || computeTokensToUsd(beforeRun?.costTokens || beforeRun?.cost_tokens),
      afterRunId: "",
      afterRunLabel: "",
      afterScore: 0,
      afterCostUsd: 0,
      status: verifyAfter ? "pending" : "not_run",
    };
  });
}


