export {
  CALENDAR_BROWSER_FOUNDATION_FRAGMENTS,
  CALENDAR_DOMAIN_RUNTIME_SCRIPT,
  CALENDAR_SCHEDULE_MODEL_FOUNDATION_SCRIPT,
  CALENDAR_SCHEDULE_MODEL_RUNTIME_SCRIPT,
  CALENDAR_PROJECTS_PAGE_ACTION_FRAGMENTS,
  CALENDAR_PROJECTS_PAGE_CONNECTOR_FRAGMENTS,
  CALENDAR_PROJECTS_PAGE_DATA_FRAGMENTS,
  CALENDAR_PROJECTS_PAGE_SHELL_FRAGMENTS,
  CALENDAR_PROJECTS_PAGE_VIEW_FRAGMENTS,
  CALENDAR_SHELL_SCRIPT_FRAGMENTS,
  CALENDAR_STYLE_FRAGMENTS,
  CALENDAR_VENDOR_HEAD_HTML,
} from "./client/index.mjs";

export { createCalendarService } from "./server/index.mjs";
