steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "BASE_IMAGE=${_BASE_IMAGE}"
      - "-t"
      - "${_IMAGE_URI}"
      - "-f"
      - "repos/runner-web-sdk/deployment/platform/Dockerfile.github-connector-overlay"
      - "."
images:
  - "${_IMAGE_URI}"

options:
  logging: CLOUD_LOGGING_ONLY
